### ISSUE TITLE
Plugin is not detected

### ISSUE THREAD

**Issue by lepaff** [ethercreative/simplemap#1]
Hi,

thanks for this nice plugin.
I discovered one problem while deploying to my stage server. 
The repository´s name is in CamelCase and was therefore not detected by Craft (2.6+).
Locally it worked fine on my mac but the server seems to be somewhat more strict regarding case sensitivity.
I forked your repo and simply renamed it to solve that.

Cheers,
Michael

**Comment by Tam** [comment]
Thanks for letting us know! I've re-named the repo to all lower case, that should make everyones lives easier.
