### ISSUE TITLE
Not outputting address / latitude & longitude 

### ISSUE THREAD

**Issue by RachnaChohan** [ethercreative/simplemap#10]
When trying to add a address in the text field (that's provided) & saving it. The text field is still blank & looking at the console log its returning  data-latitude="0.00000000" data-longitude="0.00000000". The only time a address displays in the text field is when I physically grab the pin (on the map) and drag it to a location. Then there are values in the data-latitude & data-longitude. But this is sorta a pain if I am trying to put in a specific location.

Not really sure where to go from here

I'm using the Simple Map version 1.2.3 & Craft 2.6.2796
![screenshot-simplemap](https://cloud.githubusercontent.com/assets/11861217/16916692/6ade022c-4cfe-11e6-85a9-ca9b30978133.png)

**Comment by Tam** [comment]
Hi @RachnaChohan,

Currently you need to press enter/return after pasting an address into the field to get the map to register a change. We'll fix this in a future release!

**Comment by Tam** [comment]
Fixed in [v1.2.4](https://github.com/ethercreative/simplemap/releases/tag/v1.2.4)
