### ISSUE TITLE
Coordinates stopped to load in twig templates

### ISSUE THREAD

**Issue by luizhv** [ethercreative/simplemap#100]
### Description

After update craft 2 and simple map plugin, coordinates stopped to load in twig templates, I can see the coordinates in the CP and if I click to save, it saves and the coordinates for that entry comes in twig, but the problem is that I have 850 entries, I tried to change the section to re-save all entries, it re-saves all the entries but I still can't see the coordinates in twig, the only way to get the coordinates back is going on by one and click save in the CP.

Thanks!

### Steps to reproduce

1. Update Craft 2
2. Update Simple Map

### Additional info

- Craft version: 2.6.3017
- SimpleMap version: 1.8.2
- PHP version: 7.1.14

**Comment by Tam** [comment]
We're not really supporting Craft 2 anymore, but it is now possible to upgrade Maps from Craft 2 to Craft 3 in the latest release (3.4.x).
