### ISSUE TITLE
Craft 3 add Simple Map in entry through plugin

### ISSUE THREAD

**Issue by limesquare-nl** [ethercreative/simplemap#102]
### Description
Can't add Simple Map entry through plugin in Craft CMS 3. I've found on stackexchange a post with the solution.

### Steps to reproduce

1. [Link](https://craftcms.stackexchange.com/questions/25331/craft-3-add-simple-map-in-entry-through-plugin)

### Additional info

- Craft version: 3.0.21
- SimpleMap version: 3.3.3
- PHP version: 7.1.17
- Database driver & version: MySQL 5.5.60

**Comment by limesquare-nl** [comment]
Any updates on this one?

**Comment by limesquare-nl** [comment]
Any update on this one? The problem is that you can only set a 'map' field in a plugin through a POST request. It would be better if you check if $value is set.

**Comment by Tam** [comment]
You should be able to set the properties of the map field as you would any other field in craft. I'd recommend updating to the latest release, which has re-worked how the data is saved.
