### ISSUE TITLE
Save `place_id` in `parts`?

### ISSUE THREAD

**Issue by rungta** [ethercreative/simplemap#103]
### Description

The [Geocoding API documentation][docs] says that it also returns a `place_id` as part of its results. Is this discarded from the results before it is cached in the `parts` object? Will it be possible for this to be made available?

[docs]:https://developers.google.com/maps/documentation/geocoding/intro#Results

### Steps to reproduce

1. Create a new SimpleMap field
2. Save an entry with the SimpleMap field and search for a spot, e.g. “Taj Mahal”
3. `{{ dump(mapField.parts.place_id) }}`

### Additional info

- Craft version: 3.0.21
- SimpleMap version: 3.3.3

**Comment by Tam** [comment]
We've updated the plugin to work with various other mapping services, and since this is very specific to a single service we won't be adding support for it.
