### ISSUE TITLE
Use Mapbox in CMS instead of Google Maps

### ISSUE THREAD

**Issue by bymayo** [ethercreative/simplemap#106]
### Description

It would be good if you could use Mapbox as opposed to Google Maps in the CMS. I know it's an option for front end, but it would be good if existed in the CMS also.

The main reason for this is that Google Maps recently changed their pricing and it has become too costly for our clients. (11,000 requests per month for Google Maps as opposed to 50,000 requests per month for Mapbox for free)

**Comment by jdsimcoe** [comment]
@bymayo It looks like this plugin just uses the Google Maps API to do lookup and store the LatLong entries in Craft. Per the site's instructions it shows how you can integrate with Mapbox:

https://github.com/ethercreative/simplemap/blob/v3/README.md

**Comment by bymayo** [comment]
@jdsimcoe Yeah, it would just be good to have the option to choose the map API (Whether this is Mapbox or Google Maps) that displays in the admin field.

We're outputting the Mapbox map on the front end, but this still requires us to have Google Maps API key for just the admin area.

**Comment by jdsimcoe** [comment]
@bymayo agreed.

**Comment by Tam** [comment]
You can now use Mapbox, Apple MapKit, OpenStreetMap, Wikimedia maps, Here, and Carto as well as Google Maps in the latest release ([3.4.0](https://github.com/ethercreative/simplemap/releases/tag/3.4.0))!

**Comment by bymayo** [comment]
@Tam Oh jeeeeez this is a big game changer 💯 We needed a Mapbox field last week for a project, and ended up hacking around it... 👍

**Comment by jdsimcoe** [comment]
@Tam @bymayo Seriously! I just hooked up a custom Apple MapsKit map embed on my site. So slick! I really hope you support templating for all the of the main map platforms (including MapKit).
