### ISSUE TITLE
Simple Map query only works for current section

### ISSUE THREAD

**Issue by maxstrebel** [ethercreative/simplemap#107]
### Description
When I query entries by distance, only entries related to the current section appear. I can't wrap my head around this. Is this an error?

### Steps to reproduce

1. `{% set closest = craft.entries.simplemap({
          location: { 'lat': entry.simplemap.lat, 'lng': entry.simplemap.lng }
        }).orderBy('distance').all() %}`
2. I get all entries from the current section that match the default 50km.
3. `{% set closest = craft.entries.section('anotherSection').simplemap({
          location: { 'lat': entry.simplemap.lat, 'lng': entry.simplemap.lng }
        }).orderBy('distance').all() %}`
4. No results (though I have results close to the current lat/lng in the 'anotherSection'

### Additional info

- Craft version: 3.0.24
- SimpleMap version: 3.3.4

---

thanks for this great plugin btw.

**Comment by Tam** [comment]
Weird, I can't re-create this. I take it your map field has the handle `simplemap`?

**Comment by maxstrebel** [comment]
Yes, the handle is simplemap and the same field is used in both sections.

So quering across sections should work, right?

**Comment by Tam** [comment]
It does in my tests, and there's no reason why specifying a section would stop it from working.

Can you confirm the following:
1. `anotherSection` has the `simplemap` field
2. `entry` is the same in both examples
3. Getting all entries without specifying a section returns entries from `anotherSection`

**Comment by maxstrebel** [comment]
Sorry, my bad. I just changed the field handle and it works now. I don't understand how this could be a problem but now it works. Sorry for bothering you and thank you for your time!
