### ISSUE TITLE
Field broken by dispatchEvent in IE11

### ISSUE THREAD

**Issue by samjoneill** [ethercreative/simplemap#108]
### Description

Instance of `dispatchEvent` in callback function on line 201 of `SimpleMap_Map.js` breaks map fields in IE11.

Resolved by replacing function with:

```
callback: function () {
	var event = document.createEvent("Event");
	event.initEvent('SimpleMapsGAPILoaded', true, true);
	document.dispatchEvent(event);
}
``` 

### Additional info

- Craft version: 3.0.25
- SimpleMap version: 3.3.4
- PHP version: 7.1.21

**Comment by Tam** [comment]
Fixed in 3.4.x
