### ISSUE TITLE
Q: How do I display the actual map on the front-end?

### ISSUE THREAD

**Issue by swthate** [ethercreative/simplemap#11]
Hi there,

This plugin looks like what I need: a simple, straight-forward Google Map field. I don't need all the bells and whistles that so many other plugins seem to have.

Having said that, I'm a little concerned as I haven't found a way to display my map on my entries' template. Is this plugin just for extracting data from the location set in the backend, or am I able to show the map itself?

Sorry if this is a completely noob question... I'm just getting started with Craft :)

Thanks!

**Comment by Tam** [comment]
Hi @swthate,

The plugin returns an array containing `lat`, `lng`, and others (see [docs](https://github.com/ethercreative/simplemap#usage)). You can use these as the location for any front-end map library (e.g. [Google Maps](https://developers.google.com/maps/documentation/javascript/tutorial) or [Mapbox](https://www.mapbox.com/)).

Using Google Maps as an example:

```twig
<div id="map"></div>
<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: {{ entry.myMapField.lat }},
        lng: {{ entry.myMapField.lng }}
      },
      zoom: 8
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap" async defer></script>
```

And Mapbox:

```twig
<script src='https://api.mapbox.com/mapbox-gl-js/v0.21.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v0.21.0/mapbox-gl.css' rel='stylesheet' />

<div id='map' style='width: 400px; height: 300px;'></div>
<script>
  mapboxgl.accessToken = 'pk.eyJ1IjoiZXRoZXJjcmVhdGl2ZSIsImEiOiJjaWhjMDQ4cDUwMDg0dm9ranV3ZWZtY3B2In0.KQKSKysuha7MW19Q_cCJCA';
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [
      {{ entry.myMapField.lng }},
      {{ entry.myMapField.lat }}
    ]
  });
</script>
```

**Comment by swthate** [comment]
ah-ha. Thanks a bunch, I'll give this a whirl!
