### ISSUE TITLE
Location disappearing in combination with Matrix field (manage blocks on per site basis)

### ISSUE THREAD

**Issue by jeroenlammerts** [ethercreative/simplemap#110]
### Description

Simplemap location will be empty when using it in a matrix field and change the option "manage blocks on per site basis" after adding content. I have multiple sites installed: dutch and english.

Note:
I have the same issue with the supertable plugin, https://github.com/verbb/super-table/issues/203
All default craft fields do not have this problem

### Steps to reproduce

1. Create a matrix field, do not check "manage blocks on per site basis."
2. Add one blocktype with one Simplemap field, not translatable
3. Assign the matrix field to an entry type
4. Add an entry and choose a location in the Simplemap field, save
5. Turn on the switch "manage blocks on per site basis" for the matrix field
6. Go to the entry and save it for the first site (dutch)
7. Go to the second site version (english) of the entry, the Simplemap field will be empty

### Additional info

- Craft version: Craft Pro 3.0.26.1
- SimpleMap version: 3.3.4
- PHP version: 7.1.14
- Database driver & version: MySQL 5.7.12
- Other Plugins: Field Manager, Freeform Pro, Mix, Redactor, SEOMatic, Super Table

**Comment by brandonkelly** [comment]
Have a hunch that craftcms/cms@c017661317cbf1bcedc4ee7d16d8657bcbccde26 fixed this.

**Comment by Tam** [comment]
@jeroenlammerts Is this still an issue? Might be worth updating to the latest version as well.
