### ISSUE TITLE
Parts not available via CraftQL

### ISSUE THREAD

**Issue by rogertinch** [ethercreative/simplemap#111]
Using CraftQL to expose address data using this plugin, but it doesn't look like `parts` data is coming through.

### Steps to reproduce
1. Install plugin
2. Add Google API key with no restrictions
3. Create field with the following settings:
- Restrict by Country: United States
- Restrict by Type: Precise Address
4. Create CraftQL query:
```
    ... on VenuesBar {
    	id
      title
      address {
        lat
        lng
        address
        parts {
          street_number
          street_number_short
          postal_code
          postal_code_short
        }
      }
    }
```
5. Query returns:
```
      {
        "id": 446,
        "title": "Glass Half Full - Lakeline",
        "address": {
          "lat": "30.475488853",
          "lng": "-97.804184454",
          "address": "F, 14028 US-183, Austin, TX 78717, USA",
          "parts": {
            "street_number": "",
            "street_number_short": "",
            "postal_code": "",
            "postal_code_short": ""
          }
        }
      }
```
### Additional info
- Craft version: 3.0.26.1
- SimpleMap version: 3.3.4
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Other Plugins: CraftQL 1.1.0

**Comment by KatieMFritz** [comment]
Possibly related: #113

**Comment by evanwarner** [comment]
@tinchalamo I think I've solved this one. See my [comment](https://github.com/ethercreative/simplemap/issues/113#issuecomment-443562759) on #113.
