### ISSUE TITLE
Parts no longer working?

### ISSUE THREAD

**Issue by KatieMFritz** [ethercreative/simplemap#113]
### Description
Several months ago, I set up an address field and used parts to format it. I noticed a couple months ago that while the map was still displaying correctly, the address wasn't showing up in my template. Today I did some troubleshooting, and I can show the full address with `{{ myfield }}` and list an empty array of `parts` labels, but I don't get actual data for any parts. I tried four different addresses in case the problem was with the specific address.

### Steps to reproduce

1. Add a `physicalLocation` map field to Globals > Contact Info.
2. Search for `1000 S Washington Ave, Lansing` in the dropdown list and select the option that matches.
3. In a template, `{{ contactInfo.physicalLocation }}` returns `1000 South Washington Avenue, Lansing, MI, USA`.
4. In a template, `{{ contactInfo.physicalLocation.lat }}` returns `42.722965800` and the map displays correctly.
5. In a template, the following code returns a list of part names with no data:
```html   
            <ul>
            {% for key, part in contactInfo.physicalLocation.parts %}
              <li>{{ key }}: {{ part }}</li>
            {% endfor %}
            </ul>
```

### Additional info

- Craft version: Pro 3.0.28
- SimpleMap version: 3.3.4
- PHP version: 7.1.16
- Database driver & version: MySQL 8.0.12
- Other Plugins: 
![screen shot 2018-10-25 at 2 26 55 pm](https://user-images.githubusercontent.com/7085184/47521847-15446a80-d862-11e8-848c-70f7e2d53ccb.png)

**Comment by evanwarner** [comment]
I'm just using SimpleMap for the first time and I encountered this exact issue. I think I've found the culprit:

Google's Geocoding and Places APIs are both categorized as [Web Service APIs](https://developers.google.com/maps/apis-by-platform#web_service_apis). These APIs **cannot** be accessed with API keys that have HTTP referrer restrictions; [only IP restrictions](https://developers.google.com/maps/faq#browser-keys-blocked-error).

Indeed, any entries saved while my API key has an HTTP referrer restriction end up with an empty `parts` column in the database.

Although It's not clear at all in the plugin documentation, I believe this is the reason for the **Alternate Server API Key** field in the plugin settings. This field should have a non- or IP-restricted API key in it, while the **Google Maps API Key** setting should be your referrer-restricted API key that the Maps Javascript API uses. This is my current setup and it seems to be working.

**Comment by LouisCuvelier** [comment]
@evanwarner is this still working ?

I'm not able to get parts even with your solution 😕

**Comment by evanwarner** [comment]
@LouisCuvelier it's still working for me.

**Comment by LouisCuvelier** [comment]
@evanwarner just to be sure, am I doing right ?

**Google Maps API Key** : HTTP referrer only
- Maps JavaScript API
- Geocoding API
- Places API

**Alternate Server API Key** : IP only
- Geocoding API

**Comment by evanwarner** [comment]
@LouisCuvelier Nope, set it up this way:

**Google Maps API Key :** HTTP referrer restricted
- Maps JavaScript API

**Alternate Server API Key :** IP restricted (or no restriction)
- Geocoding API
- Places API

**Comment by LouisCuvelier** [comment]
This is working. Thanks !

**Comment by Tam** [comment]
We've reworked how parts work in the latest release ([3.4.0](https://github.com/ethercreative/simplemap/releases/tag/3.4.0)) which should help resolve your issue.
