### ISSUE TITLE
Geocoder failed as a result of REQUEST_DENIED

### ISSUE THREAD

**Issue by NickToye** [ethercreative/simplemap#114]
I am working on localhost, and I have even removed all restrictions from my API key just to see if I can get this to work.

### Steps to reproduce

1.  I have a map field setup as a global.
2. I go to put in my address and I get the above error.

### Additional info

- Craft version: 3.0.28
- SimpleMap version: 3.3.4
- PHP version: 7.1.12
- MySQL 5.6.38

**Comment by Tam** [comment]
Can you confirm that you have the geocoding API enabled on your API key. You'll also need billing enabled the project your API key is from.

**Comment by NickToye** [comment]
Yeah that's got it.  Rookie error.
