### ISSUE TITLE
Map not working when editing entry

### ISSUE THREAD

**Issue by McCrisp** [ethercreative/simplemap#116]
Hi,

I cant seem to get maps working in the CP.
Our api project is up and running, everything seems ok on google console.

The map displays, but we can not search for locations, we get the following error in browser console:

`This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/places_backend?project=_ 
For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key`

Note that the project= part of the link is blank, should there not be something there?
The only configuration options for simplemaps are API'keys

**Comment by bryantAXS** [comment]
I'm running into this issue as well. Any thoughts on this?

**Comment by alexjcollins** [comment]
So after you created your project did you add the following APIs to it?
- Maps Javascript API
- Geocoding API
- Places API

The error doesn't suggest it, but it might also bee worth checking your credentials to see if you've restricted your API key so that it doesn't work.

**Comment by alexjcollins** [comment]
@McCrisp @bryantAXS Hey both, did you manage to resolve your issues or are you still running into problems?

**Comment by bryantAXS** [comment]
@alexjcollins yeah it looks like it's resolved for me. There must be a fairly significant delay after you set up your API key. I was probably testing for an hour or two after installing it and still seeing the issue. Now though it looks to be working on a few different projects that were previously erroring.

Thanks!

**Comment by alexjcollins** [comment]
@bryantAXS Glad to hear it! :)
