### ISSUE TITLE
Duplicate set returned when querying by distance

### ISSUE THREAD

**Issue by evanwarner** [ethercreative/simplemap#117]
### Description
Running an entry query with a distance search included gives me a resulting set of entries that has two of each. If my entry query has a `limit` parameter, that limit is honored, but still the limited set is doubled.

### Steps to reproduce

```
{% set myQuery = craft.entries({
  section: 'mySection',
  id: 'not ' ~ entry.id,
  limit: 3
}).myMapField({
  location: {
    lat: entry.location.lat,
    lng: entry.location.lng
  },
  radius: 500,
  unit: 'mi'
}).orderBy('distance').all() %}
```
This correctly finds the three nearest entries within 500 miles, but returns a set of 6, with two of each entry.

### Additional info

- Craft version: 3.0.34
- SimpleMap version: 3.3.4
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Other Plugins: Contact Form 2.2.3, Redactor 2.1.6, SEO 3.4.4, SuperSort 3.0.1, Super Table 2.0.14

**Comment by Tam** [comment]
Can you try again with the latest release ([3.4.0](https://github.com/ethercreative/simplemap/releases/tag/3.4.0)) and let me know if it's still an issue?
