### ISSUE TITLE
Despite pseudo-eager fetching, Elements still generate DB queries on instantiation

### ISSUE THREAD

**Issue by AugustMiller** [ethercreative/simplemap#119]
### Description

When Elements are instantiated, it appears as though `normalizeValue()` dips back into the DB—this is causing N+1 queries, even inside a loop of eager-loaded elements.

This happens prior to any uses of the Elements—as soon as the query is executed, the Elements are created, and the SimpleMap field is "normalized."

I figured there would be enough information pulled through the modified `ElementQuery` to avoid this, but the queries still punctuate an otherwise quiet output of some eager-loaded elements…

### Additional info

- Craft version: 3.0.37
- SimpleMap version: 3.3
- PHP version: 7.1.22
- Database driver & version:
- Other Plugins: —

**Comment by Tam** [comment]
Fixed in the latest release ([3.4.0](https://github.com/ethercreative/simplemap/releases/tag/3.4.0)).
