### ISSUE TITLE
part street_address empty

### ISSUE THREAD

**Issue by MarkOlijslagers** [ethercreative/simplemap#123]
### Description
The output for {{ entry.addressField.part.street_address }} doesn't return the correct value.
After looping through the parts with a for-loop, i saw the value was returned by the part route {{ entry.addressField.part.route }}.

Is this filed mapped wrong in the plugin?

### Additional info
- Craft version: 3.1.15
- SimpleMap version: 3.3.5
- PHP version: 7.2

**Comment by shoored** [comment]
I seem to have the same issue, but all parts return empty.

### Additional info

- Craft version: 3.1.17.2
- SimpleMap version: 3.3.5
- PHP version: 7.2

**Comment by Tam** [comment]
We've reworked how parts works in the latest update ([3.4.0](https://github.com/ethercreative/simplemap/releases/tag/3.4.0)) which should help resolve your issue.

**Comment by MarkOlijslagers** [comment]
Thanks,nice job!
