### ISSUE TITLE
[FR] Field has default values hardcoded - abstract to settings

### ISSUE THREAD

**Issue by BridgingUnit** [ethercreative/simplemap#124]
SimpleMap 3.3.5

/src/fields/MapField.php has lat, lng, zoom, height all hardcoded as public variables.

These get used to generate the default map view, both that seen in the field's settings (where they can be overridden if you manually recenter it), but also, if that's not overridden, in the map shown in an entry which has the field too.

It'd be great if these could instead be configured via plugin settings/config, like the API key, so that these defaults are exposed for easier editing.

It'd also be great if the settings for the field had an address search to more quickly zero in on a default lat/lng to centre the map on and save you having to manually guess. Like it eventually and already has in the entry field display itself.

Thanks.

**Comment by Tam** [comment]
The latest release (3.4.x) allows you to search for a default location. We're not going to put the default field values in the plugin settings since you're supposed to set them on a per-field basis.
