### ISSUE TITLE
Update from 3.3.5 to 3.4.3 eleminates all the data

### ISSUE THREAD

**Issue by elfacht** [ethercreative/simplemap#129]
### Description

Update from 3.3.5 to 3.4.3 kills all the data and leave the fields empty. On a website with more than 100 entries using this field this is a bit of a hazzle. Is there any chance to keep the data and updating the plugin?

**Comment by alexjcollins** [comment]
Hey @elfacht It shouldn't be doing that so we'll definitely check that out for you. Did you get any errors during or after the update?

**Comment by elfacht** [comment]
Hey @alexjcollins thanks for having a look. I didn't get any errors, I just did it simultaniously with an Craft update from 3.1.17.1 to 3.1.19.

**Comment by elfacht** [comment]
Maybe this helps:

**Before the update:**

![Screenshot 2019-03-21 um 20 51 27](https://user-images.githubusercontent.com/529443/54780923-4e1f1a80-4c1b-11e9-8195-abe7210431f8.jpg)
![Screenshot 2019-03-21 um 20 51 37](https://user-images.githubusercontent.com/529443/54780925-4eb7b100-4c1b-11e9-983a-4e2c676ad5e7.jpg)

**After the update**

![Screenshot 2019-03-21 um 20 52 19](https://user-images.githubusercontent.com/529443/54780926-4eb7b100-4c1b-11e9-9bf2-d918ecddf754.jpg)
![Screenshot 2019-03-21 um 20 52 30](https://user-images.githubusercontent.com/529443/54780927-4eb7b100-4c1b-11e9-9ac9-368d8f806639.jpg)


Beside that, the new fields doesn't save the data with the API keys.

**Comment by Tam** [comment]
@elfacht Did the update migration run successfully? Could you check the contents of your `simplemaps` table and ensure there's data there?

**Comment by elfacht** [comment]
@Tam No errors, but all entries are getting new `dateCreated` and `dateUpdated` values (time of the update). And a new entry got created which has emtpy values:

```
INSERT INTO `bnb_simplemaps` (`id`, `elementId`, `ownerId`, `ownerSiteId`, `fieldId`, `lat`, `lng`, `zoom`, `address`, `parts`, `dateCreated`, `dateUpdated`, `uid`)
VALUES
	(107, 1868, 1761, 1, 258, 0.000000000, 0.000000000, 15, '', '{\"number\":\"\",\"address\":\"\",\"city\":\"\",\"postcode\":\"\",\"county\":\"\",\"state\":\"\",\"country\":\"\"}', '2019-03-22 15:29:29', '2019-03-22 15:29:29', '13297fa3-8e6a-418a-a789-6841ed1dd894');
```

Maybe it's the new type of the Array?

![Screenshot 2019-03-22 um 16 37 09](https://user-images.githubusercontent.com/529443/54834617-cbe93180-4cc0-11e9-9741-38c6ed2d5eb2.jpg)

**Comment by Tam** [comment]
@elfacht Just released 3.4.4, can you try upgrading directly to it and let me know if it fixes your issues.

**Comment by elfacht** [comment]
@Tam Unfortunately not. The only data I can extract from the field are `lat`, `lng` and `zoom`. `parts` is not working anymore and still an empty entry will be created:

![Screenshot 2019-03-25 um 09 24 34](https://user-images.githubusercontent.com/529443/54904844-d897a080-4edf-11e9-938b-e303fc0bf6af.jpg)

My template before the update:

```
{% set street = item.googlePlace.parts.route_short ?? null %}
{% set street_no = item.googlePlace.parts.street_number ?? null %}
{% set zip = item.googlePlace.parts.postal_code ?? null %}
{% set city = item.googlePlace.parts.locality ?? null %}
```

It doesn't throw any errors, they're just empty even though the database entries are not.

**Update**

Maybe this error helps when I try to get `item.googlePlace.parts.street_number`:

`Neither the property "street_number" nor one of the methods "street_number()", "getstreet_number()"/"isstreet_number()"/"hasstreet_number()" or "__call()" exist and have public access in class "ether\simplemap\models\Parts".`

**Comment by Tam** [comment]
Are existing maps (from before the upgrade) working correctly? Is it just new maps that error?

**Comment by elfacht** [comment]
@Tam The bug occurs on all existing maps, but also the new map field doesn't save the data. But my biggest problem are over 100 existing entries with the map field.

**Comment by Tam** [comment]
@elfacht Have you updated to 3.4.6 (just released) and tried again?

**Comment by elfacht** [comment]
@Tam This worked!

But now new fields won't work proberly. They'll getting the suggestions and won't throw an error, but the DB input is empty:

![Screenshot 2019-03-25 um 15 09 13](https://user-images.githubusercontent.com/529443/54926190-19a7a900-4f10-11e9-8598-a20dc3490f86.jpg)

**Template**

![Screenshot 2019-03-25 um 15 09 19](https://user-images.githubusercontent.com/529443/54926192-19a7a900-4f10-11e9-90b3-a47b553fc015.jpg)

**DB**

![Screenshot 2019-03-25 um 15 10 55](https://user-images.githubusercontent.com/529443/54926264-38a63b00-4f10-11e9-8b3a-5e0f069f84e5.jpg)

**Comment by Tam** [comment]
@elfacht Are you using Google Maps for geo-coding?

**Comment by elfacht** [comment]
@Tam Yes, and the API key seems to work.

**Comment by elfacht** [comment]
Now I'm getting JS errors in the CP when I try to clear the field:

```
TypeError: "e.value.parts is null"
```

~~Also:~~

```
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.
```

~~It's a bit unclear which API used in which field. In the prior version I used the restricted and a non-restricted API key. Is this still nessesary?~~

**Update**

Before saving the entry:

![Screenshot 2019-03-25 um 15 36 16](https://user-images.githubusercontent.com/529443/54928165-cb94a480-4f13-11e9-9c9a-68066ee86e61.jpg)

After saving the entry only the name and country will be saved.

**Comment by Tam** [comment]
Just released 3.4.7 which should fix the JS issues / missing address parts. Do you have any other plugins that use the Google Maps JS API? Maps will only include it once, no matter how many fields are on the page so it's most likely another plugin including it as well.

**Comment by elfacht** [comment]
Thanks, that worked! `route_short` is deprecated now? Using `route` should be fine for me.

**Comment by Tam** [comment]
Technically any parts that don't appear on the address fields inputs are deprecated, but they all still work for the sake of backwards compatibility. The availablilty of those parts is down to the whim of Google and what data they return.
