### ISSUE TITLE
Center to the initial location without marker and clear the address/marker

### ISSUE THREAD

**Issue by martinleveille** [ethercreative/simplemap#131]
It would be great if the map could be centered to the initial location without a marker. This will clearly indicate to the user that there is no saved address for that field and it will also not populate by default the `lat` and `lng` of the initial location.

Also we need an option to clear the address/marker/lat/lng/parts from the map, like this feature request #93 

Right now, we do not have a clear way to figure out if the Map field is filled or not because `lat` and `lng` are always there.

### Additional info

- Craft version: 3.1.19
- SimpleMap version: 3.4.3

**Comment by Tam** [comment]
It's possible to drag the marker to select a location, hiding the marker would remove this functionallity so we won't be doing it. The field now always shows the full address (non-editable if the address fields are hidden) so it's clear whether the field has content or not.
