### ISSUE TITLE
Location search field is empty when only showing this field

### ISSUE THREAD

**Issue by martinleveille** [ethercreative/simplemap#132]
When you only show the Location search field, there is no way for a user to know if an address is already saved with these settings:

- hideSearch: false
- hideMap: true
- hideAddress: true

If an address is already saved in the Map field, there is no clue to know what address already exists.

### Additional info

- Craft version: 3.1.19
- SimpleMap version: 3.4.3

**Comment by Tam** [comment]
We're always showing the "full address" field non-editable if the address fields are hidden as of 3.4.6.
