### ISSUE TITLE
Error importing to via Feed Me: Access to undeclared static property

### ISSUE THREAD

**Issue by BridgingUnit** [ethercreative/simplemap#134]
Hi,

I'm getting an error running an import via Feed Me into a Map field.

The Feed Me log flags up the following error, and then bails out from any import at all: 

Access to undeclared static property: ether\simplemap\SimpleMap::$plugin - SimpleMap.php: 94

Error suggests it's something here, but it might be something in Feed Me.... Apologies if that's so.

Thanks for any help.

Latest version of Craft (3.1.19), FeedMe (3.1.16) and Map (3.4.4)

**Comment by engram-design** [comment]
@BridgingUnit Yep, best to keep this under Feed Me, as the implementation is with us. This can be closed and I'll follow up on the Feed Me repo.
