### ISSUE TITLE
The Map field do not translate per site

### ISSUE THREAD

**Issue by martinleveille** [ethercreative/simplemap#136]
### Description

When you set the Map field to be translated per site, it do not translate.

### Steps to reproduce

1. Install Craft and setup 2 sites.
2. Create a channel section.
3. Create a Map field, select `Translate for each site` and add it to the section field layout.
4. Create an entry in that section and select an address in the Map field.
5. Edit the same entry for the second site and select another an address in the Map field.
6. The address in all sites are now the same.

### Additional info

- Craft version: Craft Solo 3.1.19
- SimpleMap version: 3.4.4
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.25
- Other Plugins: No

**Comment by Tam** [comment]
Fixed in 3.4.6
