### ISSUE TITLE
Runtime Error – political_* fields not available

### ISSUE THREAD

**Issue by mattrothenberg** [ethercreative/simplemap#137]
### Description
I just upgraded to `3.4.4` from `3.3.4`, and my site is broken. I have a template where I read properties thusly, but these fields seem to have disappeared upon upgrading.

```
{% if location.parts.political_short %}
    {{location.parts.political_short}},
  {% endif %}
```
Even in the admin panel, where there used to be a complete field for **Event Location**, I'm now presented with a blank set of fields.

<img width="839" alt="Screen Shot 2019-03-23 at 1 25 55 PM" src="https://user-images.githubusercontent.com/5148596/54869484-42dd0380-4d6f-11e9-9859-894e746df7a5.png">

Any ideas what could have gone wrong during this upgrade? Am I doing something silly here?

### Steps to reproduce
1. Upgrade from `3.3.4` to `3.4.4`
2. Observe broken front-end and empty fields in admin panel

### Additional info

- Craft version: `latest`
- SimpleMap version: `3.4.4`
- PHP version: `7.3.2`
- Database driver & version: `MySQL 8.0.13`

**Comment by Tam** [comment]
Fixed in 3.4.6
