### ISSUE TITLE
array_merge(): Argument #2 is not an array - MapService.php: 325

### ISSUE THREAD

**Issue by BridgingUnit** [ethercreative/simplemap#138]
I'm using Feed Me to populate entries which include a Simple Map field.

My feed only provides lat, lng and zoom. No address.

It looks like _populateMissingData() in MapService.php within Simple Map is running off to Google (in my build) via _addressFromLatLng_Google() in the GeoService.php and pulling back an object generated via line 812:

`			'parts' => new Parts($pos['address_components'], GeoEnum::GoogleMaps),`

This is all working fine. I've logged it and checked.

But what's returned is an object, not an array, and line 325 in MapService.php tries to array_merge it:

```
			$record->parts = new Parts(
				array_merge(
					(array) $record->parts,
					$loc['parts']
				)
			);
```

If instead you typecast the returned object, then all works fine for me:

```
			$record->parts = new Parts(
				array_merge(
					(array) $record->parts,
					(array) $loc['parts']
				)
			);
```

But you may prefer to take a different tack. I don't know what other values might be returned as $loc['parts'] via other services etc.

Latest version of Craft (3.1.19), FeedMe (3.1.16) and Map (3.4.4)

**Comment by Tam** [comment]
Fixed in 3.4.6
