### ISSUE TITLE
Can't save location in CP

### ISSUE THREAD

**Issue by admanami** [ethercreative/simplemap#139]
### Description

After updating to Maps 3.4.4 can't save location in CP.

### Steps to reproduce

1. Add a location via the Maps field in an entry in the CP
2. Save the entry

Outcome: Craft shows an error, the location is not saved.

### Additional info

- Craft version: 3.1.19
- SimpleMap version: 3.4.4
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.25
- Other Plugins: Google cloud storage, redactor, units.
<img width="447" alt="Screen Shot 2019-03-24 at 9 57 46 pm" src="https://user-images.githubusercontent.com/6200995/54878417-b91d5b00-4e80-11e9-9f89-173d5a1d2101.png">

**Comment by Tam** [comment]
@admanami Can you upgrade to 3.4.6 and try again?
