### ISSUE TITLE
Error Calling unknown method

### ISSUE THREAD

**Issue by richhayler** [ethercreative/simplemap#151]
### Description
I am attempting to use this plugin for setting an address within the globals section of the control panel and getting this error when attempting to display the output on a site template.
If I use `{{ global.myMap.address }}` it outputs the full address including the city, state and postcode when I was just expecting the street address. When I attempt to use `{{ global.myMap.city }}` or any of the the other address elements, e.g. state, postcode etc I get the above error.

### Steps to reproduce

1. Create a new map field named "myMap"
2. Add to a globals set named "global"
3. Add data
4. Use {{ global.myMap.city }} in a site template
5. Load the template in the browser

### Additional info

- Craft version: 3.1.20.1
- SimpleMap version: 3.4.9
- PHP version: 7.1

**Comment by Tam** [comment]
You'll need to use `{{ global.myMap.parts.city }}` to get the city and any other address parts. See [Usage](https://github.com/ethercreative/simplemap#usage).

**Comment by richhayler** [comment]
Thank you
