### ISSUE TITLE
Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by ghost** [ethercreative/simplemap#152]
### Description
I get this error when trying to save an entry with a map field
General error: 1205 Lock wait timeout exceeded; try restarting transaction
The SQL being executed was: UPDATE `craft_fields` SET `searchable`=1, `settings`='{\"lat\":15.342101,\"lng\":44.2005197,\"zoom\":15,\"country\":null,\"hideSearch\":\"1\",\"hideMap\":\"\",\"hideAddress\":\"1\",\"showLatLng\":\"\",\"hideLatLng\":null,\"height\":null,\"countryRestriction\":null,\"typeRestriction\":null,\"boundaryRestrictionNELat\":null,\"boundaryRestrictionNELng\":null,\"boundaryRestrictionSWLat\":null,\"boundaryRestrictionSWLng\":null,\"boundary\":\"\\\"\\\"\"}', `dateUpdated`='2019-04-03 13:43:21' WHERE `id`=89

### Additional info

- Craft version:3.1.20.1
- SimpleMap version: 3.4.9

**Comment by Tam** [comment]
I can't recreate this, what other plugins do you have installed and what database driver are you using?

**Comment by ghost** [comment]
Element API
Field Manager
Guest Entries
Incognito Field
Minify
Redactor
Super Table

PHP version: 7.1.10
Driver is sql

i can't delete the entry, or the field or the section. 
the search index table got marked as crashed too.

**Comment by Tam** [comment]
Can you try to save an entry and send me the stack trace from your web.log file?

**Comment by Tam** [comment]
@Sam-Black-0013 Have you had any luck with this?
