### ISSUE TITLE
Isn't working for me inside a matrix

### ISSUE THREAD

**Issue by drball** [ethercreative/simplemap#16]
I've added this as a field inside a matrix block, and it's not working when referenced in the template like this: 
{{ block.googleMap }}

It gives this error: 

> Object of class Craft\SimpleMap_MapModel could not be converted to string

However, referencing individual elements works fine, eg {{ block.googleMap.lat }}

Am I using it wrong?

**Comment by Tam** [comment]
The field returns an object containing `lat`, `lng`, `zoom`, `address`, and `parts`. In your template you would reference these `{{ block.googleMap.address }}` rather than `{{ block.googleMap }}` (which returns an array).
