### ISSUE TITLE
Preferred Country (field settings)

### ISSUE THREAD

**Issue by cole007** [ethercreative/simplemap#161]
### Description

The Preferred Country option in the Field Settings suggests that the chosen country takes precedence in results shown. However, since upgrading it looks like this restricts the responses only to the selected country.

Not sure if better to change functionality or wording on plugin but as an upgrade from Simple Maps it caught me/client out as functionality seems to have changed.

### Steps to reproduce

1. Add field
2. Specify eg UK as `Preferred Country` option
3. For field search for a location outside the selected country (eg Hong Kong)

### Additional info

- Craft version: 3.1.26
- Maps version: 3.4.11
- PHP version: 7.1.29
- Database driver & version: MySQL 5.7.26

**Comment by Tam** [comment]
@cole007 The functionallity of preferred country can differ depending on the Geo service you use. I've updated the instructions on the field to be a bit clearer and explain this better.
