### ISSUE TITLE
Parts that were available pre 3.4 no longer work

### ISSUE THREAD

**Issue by shornuk** [ethercreative/simplemap#167]
### Description
Been running maps for a while and I'm just testing the update to the new version. Mostly it's all fine, however the old `parts` that were available pre 3.4 no longer work. I thought they were meant to?
The data is there in `parts` in the database, all the new parts work but they old ones give 
```
Neither the property "administrative_area_level_1" nor one of the methods "administrative_area_level_1()", "getadministrative_area_level_1()"/"isadministrative_area_level_1()"/"hasadministrative_area_level_1()" or "__call()" exist and have public access in class "ether\simplemap\models\Parts".
```
 

### Additional info
- Craft version: Latest
- Maps version: Latest

**Comment by clarknelson** [comment]
this broke my website and my client was not happy
