### ISSUE TITLE
Undefined index: postcode

### ISSUE THREAD

**Issue by harispepic** [ethercreative/simplemap#169]
### Description
After I have searched for an address and want to save the page, I receive the following message

![Bildschirmfoto 2019-06-26 um 09 59 34](https://user-images.githubusercontent.com/25743047/60162104-21ba0200-97f9-11e9-922e-848482115d68.png)

The postal code is not filled in by typing in the address field.

### Steps to reproduce

1. Search address
2. Save in CP

### Additional info
- Craft version: 3.1.31
- Maps version: 3.5.1
- PHP version: 7.3.5
- Database driver & version: MySQL 5.7.26

**Comment by alexjcollins** [comment]
Would you be able to share the address you're searching? 
Also, what Geocoding service are you using? (Nominatim, Mapbox, Google Maps or Here)

**Comment by harispepic** [comment]
Hi @alexjcollins, thanks for your help!

The address I was searching was Zürich and I'm using Google Maps.

**Comment by alexjcollins** [comment]
Thanks for the speedy reply, I'll take a look and get back to you

**Comment by philipboomy** [comment]
Your fix fixed the problem. Thanks for quick fix.
