### ISSUE TITLE
Works in CP, how to embed into frontend?

### ISSUE THREAD

**Issue by neotheicebird** [ethercreative/simplemap#17]
Nice plugin! I am able to play with it in the control panel and it looks great. But what should I add to the frontend templates to insert it there?

I tried: 

1. Created a field called `simplemapfield`
2. Added it to a section, (About page of a demo site)

```
{{ simplemapfield }}
<simplemapfield></simplemapfield>
{% embed "simplemap/templates/map-fieldtype.twig" %}
```

I even tried copy-pasting the contents of map-fieldtype.twig into the about page template. Obviously I am undereducated in handling this part of the code. Any help would be appreciated.

**Comment by paul-frost** [comment]
[Answered in previous issue](https://github.com/ethercreative/simplemap/issues/11)
