### ISSUE TITLE
Craft 3.2 update - 

### ISSUE THREAD

**Issue by bliswebagency** [ethercreative/simplemap#170]
### Description

Unable to re-save entries with Map field data after update to Craft 3.2

### Steps to reproduce

1. Create entry with Map Address field with a Matrix field 
2. Edit and attempt to re-save Entry
Error > Database Exception – yii\db\Exception
Can not move a node when the target node is root.

### Additional info

PHP version | 7.2.19
-- | --
Linux 3.10.0-714.10.2.lve1.5.12.el7.x86_64
MySQL 10.0.38
Imagick 3.4.4 (ImageMagick 6.9.4-10)
Craft Pro 3.2.0

**Comment by alexjcollins** [comment]
Hey, just to let you know we're currently working on a fix and trying to get it out asap 🏃

**Comment by bliswebagency** [comment]
Thanks so much for your prompt update.  Fix has worked and issue resolved.  Much appreciated.

**Comment by alexjcollins** [comment]
@bliswebagency glad it all worked. Thanks, @Tam for the hard work on this release 🔥
