### ISSUE TITLE
Craft 3.2.0: Map field looses content after publishing draft on existing entry

### ISSUE THREAD

**Issue by nilsenpaul** [ethercreative/simplemap#171]
### Description
After saving ('update entry') an entry with a Maps field, the contents of the field are gone.

### Steps to reproduce

1. Create a maps field
2. Create an the entry, save it, change the Maps field's content, save it again. The content is gone.

### Additional info

- Craft version: 3.2.0
- Maps version: 3.5.2
- PHP version: 7.0.33

**Comment by codeartaus** [comment]
Also having this issue on a few sites 
--
Craft version: 3.2.1 (Happening on 3.2.1 too)
Maps version: 3.5.2
PHP version: 7.1.25

**Comment by alexjcollins** [comment]
Working on this I write this, should be an update for you soon(ish)!

**Comment by nilsenpaul** [comment]
Thanks @alexjcollins!
