### ISSUE TITLE
Filter by City

### ISSUE THREAD

**Issue by bhashkar007** [ethercreative/simplemap#172]
### Description
I have a search form which is filtering users by city (Map field). I tried to achieve it like:
```
{% set params = {
    parts: {
        city: location
    }
} %}
{% set users = craft.users.myMapField(params) %}
```
But it's not working.

Could you please guide.

### Additional info

- Craft version: 3.1.28
- Maps version: 3.4.11
- PHP version: 7.1.10
- Database driver & version: 5.0.12

**Comment by Tam** [comment]
You can use the location param to filter by city:

```twig
{% set location = 'My City' %}

{% set users = craft.users.myMapField({
    location: location,
    country: 'IN',
}).all() %}
```

If you know you're only going to be searching for cities in a specific country, you can set the country param to that countries ISO Alpha-2 code.
