### ISSUE TITLE
Updated to 3.6.1 saving map causes internal service error

### ISSUE THREAD

**Issue by stphnmartin** [ethercreative/simplemap#179]
### Description
Updated to maps 3.6.1. Saving a map results in an internal service error and the entry will not save. 
 
From the web.log:

2019-07-19 13:39:56 [-][1][187550rnhq45gn7o9r8d6oned6][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: ether\simplemap\models\PartsLegacy::postal_code_suffix in /vendor/yiisoft/yii2/base/BaseObject.php:163

### Steps to reproduce

1. Search for address in maps field, select, and save
2. Results in internal service error.

### Additional info

- Craft version: Craft Pro 3.2.4.1
- Maps version: 3.6.1
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Other Plugins:
Contact Form	2.2.5
Contact Form Templates	1.0.1
Email From Template	0.0.1
Enupal Snapshot	1.2.6
Feed Me	4.1.1
Field Manager	2.1.0
Freeform	3.2.2
Freeform submission to XML	0.0.1
Logout Redirect	2.0.1
MailChimp Lists	1.0.5
Maps	3.6.1
Redactor	2.3.3.2
SEOmatic	3.2.16
Sprout Reports	1.2.4
Store Hours	2.1.1.1
SuperSort	3.0.1
Super Table	2.2.1
Units	1.0.3
Wordsmith	3.0.5

**Comment by engram-design** [comment]
Seeing a similar error:

`Setting unknown property: ether\simplemap\models\PartsLegacy::0`

**Comment by Tam** [comment]
@stphnmartin @engram-design What geocoding service are you using, and what addresses are you searching for?

**Comment by engram-design** [comment]
All just the defaults.

Also got another issue about the content table column not being large enough - for some reason it was a `VARCHAR` instead of `TEXT` - I assume that's just something on our end gone wrong?

**Comment by Tam** [comment]
Yeah, that's fixed in the next release. To confirm, you're using Nominatim for geocoding?

**Comment by engram-design** [comment]
Sorry, just checked - Google Maps, with valid API Keys. Only solution was to ditch all fields settings in project.yaml and re-save the field.
