### ISSUE TITLE
SimpleMap: Geocoder failed as a result of REQUEST_DENIED

### ISSUE THREAD

**Issue by ineghi** [ethercreative/simplemap#18]
Happens when I select a location into the search input.
My API Key is set and working.

What could causes that ?

Thanks,

**Comment by Tam** [comment]
I haven't been able to recreate this issue. Could you let me know what version of Craft & the plugin you are using, and what browser?

**Comment by JamieUdaho** [comment]
Hi I'm getting the same console error: SimpleMap: Geocoder failed as a result of REQUEST_DENIED. I am on Chrome, just barely cloned the SimpleMap repo into my craft project.

**Comment by JamieUdaho** [comment]
Found this, not sure if this is helpful. http://stackoverflow.com/questions/3212550/google-geocoding-api-request-denied

**Comment by JamieUdaho** [comment]
Figured out my issue, even though I had enabled the google maps javascript API, it must not have fully registered as such. Once I enabled and got a new API key, everything was awesome. It wasn't an issue with SimpleMap. Thanks!

**Comment by admench** [comment]
For what it's worth, if anyone comes across this issue, I found the underlying problem: you have to enable both the 'Maps Javascript API' and 'Geocoding API' for the particular API keys used by Simple Map.

https://support.google.com/googleapi/answer/6158841?hl=en
