### ISSUE TITLE
Column already exists error when upgrading

### ISSUE THREAD

**Issue by keyurshah** [ethercreative/simplemap#187]
### Description
received this error.  thank you for looking into it.

One of Maps’s migrations failed.

Database Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'field_map_mapCenter'
The SQL being executed was: ALTER TABLE matrixcontent_contentbuilder ADD field_map_mapCenter text

Migration: ether\simplemap\migrations\m190712_104805_new_data_format

Output:

1. Creating Maps content columns 
- Create content column for Map Center in matrix map 
> add column field_map_mapCenter text to table {{%matrixcontent_contentbuilder}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'field_map_mapCenter'
The SQL being executed was: ALTER TABLE matrixcontent_contentbuilder ADD field_map_mapCenter text 

### Steps to reproduce

1. upgrading to the latest version of maps

### Additional info

- Craft version: 3.2.6
- Maps version: 3.5.2
- PHP version: 7.2.11
- Database driver & version: MySQL 5.7.24
- Other Plugins:

**Comment by MattWilcox** [comment]
I too am getting a similar error...

Database Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'field_map_map'
The SQL being executed was: ALTER TABLE c3_matrixcontent_mixedcontent ADD field_map_map text

Migration: ether\simplemap\migrations\m190712_104805_new_data_format

Output:

1. Creating Maps content columns
- Create content column for Map in matrix map
> add column field_map_map text to table {{%matrixcontent_mixedcontent}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'field_map_map'
The SQL being executed was: ALTER TABLE c3_matrixcontent_mixedcontent ADD field_map_map text

**Comment by ademers** [comment]
I'm having the same issue: https://github.com/ethercreative/simplemap/issues/180#issuecomment-514669465

**Comment by keyurshah** [comment]
Thanks for the fix, but I'm now receiving this error now:

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'content' at line 1
The SQL being executed was: ALTER TABLE matrixcontent_contentbuilder CHANGE field_map_mapCenter field_map_mapCenter content

Migration: ether\simplemap\migrations\m190712_104805_new_data_format
```

**Comment by ademers** [comment]
3.6.3 solved the issue for me. Thanks!
