### ISSUE TITLE
OVER_QUERY_LIMIT

### ISSUE THREAD

**Issue by magnusland** [ethercreative/simplemap#19]
I'm using this (great) plugin in a Matrix for a client, one row for each office they have. If we add more than three rows there is a console warning; 

> Geocoder failed as a result of OVER_QUERY_LIMIT

We can always solve this without using Matrix, but I thought I'd give you a heads up on this.

**Comment by tomfrew** [comment]
Having a similar issue here. 
I played around with random setTimeouts to delay field loading but even with that only map field loads a map.

**Comment by Tam** [comment]
Should be fixed, or at least improved, in v1.5.0!
