### ISSUE TITLE
Dragging the map marker around does not update lat/lng

### ISSUE THREAD

**Issue by sebastian-lenz** [ethercreative/simplemap#191]
The map marker in the preview is draggable (at least when using Google Maps). However, dragging the marker around does not update the latitude / longitude data.

**Comment by Tam** [comment]
@sebastian-lenz I can't re-create this. How is your field setup and is the address changing correctly?

**Comment by sebastian-lenz** [comment]
Hi, sorry, completely our fault, the Google API key we've used was stale. Keep up the great work!
