### ISSUE TITLE
Error during migration after updating to 3.6.4

### ISSUE THREAD

**Issue by harispepic** [ethercreative/simplemap#192]
### Description
When running the ./craft migrate/all command, I get the following error when the migration runs for a Maps field inside a Matrix:

`- 1 Creating Maps content columns
> Create content column for Google Maps Standort in content table
     add column field_mapLocation text to table {{%content}} ... done (time: 0.260s)
- 2 Creating new Maps table
    > create table {{%maps}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_maps' already exists
The SQL being executed was: CREATE TABLE `craft_maps` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `ownerId` int(11) NOT NULL,
        `ownerSiteId` int(11),
        `fieldId` int(11) NOT NULL,
        `lat` decimal(11,9),
        `lng` decimal(12,9),
        `dateCreated` datetime(0) NOT NULL,
        `dateUpdated` datetime(0) NOT NULL,
        `uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8`

### Steps to reproduce

1. Update Maps via composer
2. Run ./craft migrate/all

### Additional info

- Craft version: 3.2.7
- Maps version: 3.5.2
- PHP version: 7.1.26

**Comment by Tam** [comment]
@harispepic What other plugins do you have installed?

**Comment by harispepic** [comment]
Hi @Tam 

Following Plugins are installed:

Activity Log	1.0.1
Contact Form	2.2.5
Contact Form Templates	1.0.1
Element API	2.5.4
Entry Instructions	1.0.4
Expanded Singles	1.0.7
Feed Me	4.1.1
Field Manager	2.1.0
GeoMate	v1.0.6
Investment	1.0.0
Maps	3.5.2
Migration Manager	3.0.21
Navigation	1.1.13
Redactor	2.3.3.2
SEO	3.6.1.1
Super Table	2.2.1
Typogrify	1.1.18
XML Sitemap	1.0.9

**Comment by bymayo** [comment]
I've also had this issue on 2 other Craft 3 builds. It seems to create the table in the database, but then throw the error. Is it trying to create the table in another migration or something similar?

I tried to figure out at what version this errored from when upgrading to 3.6.4.1 by doing:

3.3.4 > 3.4.0
3.4.0 > 3.5.2
3.5.2 > 3.6.0
3.6.0 > 3.6.4.1

But I didn't get the error!

But going straight from 3.3.4 > 3.6.4.1 throws the error.

**Comment by Tam** [comment]
Thanks for pointing me in the right direction @bymayo!

**Comment by bymayo** [comment]
@Tam No worries! Thanks for the speed fix!

**Comment by harispepic** [comment]
@bymayo Thanks for the fix but it didn't helped out.
I'm getting a new error

Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_mapLocation' in 'field list'
The SQL being executed was: SELECT `users`.`password`, `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `users`.`username`, `users`.`firstName`, `users`.`lastName`, `users`.`email`, `users`.`admin`, `users`.`locked`, `users`.`pending`, `users`.`suspended`, `users`.`lastLoginDate`, `users`.`lockoutDate`, `users`.`photoId`, `users`.`hasDashboard`, `content`.`id` AS `contentId`, `content`.`field_addresstype`, `content`.`field_projectAlternativeDesign`, `content`.`field_salutation`, `content`.`field_bo`, `content`.`field_boxTeaserText`, `content`.`field_closing`, `content`.`field_date`, `content`.`field_default`, `content`.`field_eMail`, `content`.`field_exclusiveProject`, `content`.`field_errorMessage`, `content`.`field_forgotPasswordModal`, `content`.`field_mapLocation`, `content`.`field_heroProject`, `content`.`field_investmentPrivateText`, `content`.`field_contactEmailTo`, `content`.`field_contactSuccessMessage`, `content`.`field_shorttext`, `content`.`field_leadText`, `content`.`field_loginModal`, `content`.`field_nbo`, `content`.`field_publicLeadtext`, `content`.`field_investmentPublicText`, `content`.`field_location`, `content`.`field_preferredLanguage`, `content`.`field_projectInformation`, `content`.`field_referencesTitle`, `content`.`field_pageTitle`, `content`.`field_selligentDeactivate`, `content`.`field_selligentProject`, `content`.`field_selligentTeaserText`, `content`.`field_languageSelect`, `content`.`field_teaserText`, `content`.`field_phone`, `content`.`field_tel`, `content`.`field_text`, `content`.`field_topNews`, `content`.`field_company`, `content`.`field_sold`, `content`.`field_soldObjectsTitle`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `craft_elements` `elements`
INNER JOIN `craft_users` `users` ON `users`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
WHERE (`elements_sites`.`siteId`='1') AND (`elements`.`id`='1') AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `users`.`username`
LIMIT 1) `subquery`
INNER JOIN `craft_users` `users` ON `users`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `users`.`username`
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'content.field_mapLocation' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_mapLocation' in 'field list'

**Comment by pbmills** [comment]
Hi, I did migration from Craft 2 to Craft 3 and I am not able to install Map plugin.
<img width="1547" alt="Screen Shot 2021-10-11 at 10 11 48 AM" src="https://user-images.githubusercontent.com/31907075/136713146-ece9dec3-19e6-46a1-bd74-29b1e88f5f3a.png">
