### ISSUE TITLE
Database error on fresh install

### ISSUE THREAD

**Issue by chromadesign** [ethercreative/simplemap#193]
### Description
Error message saying "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_map' in 'field list'" right after installing. "./craft migrate/all" doesn't help. 

### Steps to reproduce

1. Upgraded a Craft 2 install to Craft 3 (site running fine after upgrade)
2. Installed plugin from the plugin store.

### Additional info

- Craft version: 3.2.8
- Maps version: 3.6.4.1
- PHP version:  7.3.1 
- Database driver & version: MySQL 5.5.5
- Other Plugins: Neo, Seomatic, Imager

**Comment by Tam** [comment]
@chromadesign Was Simplemap installed on the Craft 2 version of the site, or was it added new to the Craft 3 version?

**Comment by chromadesign** [comment]
It was installed, yes. Which is why I thought the migrate command would help.

**Comment by Tam** [comment]
Can you share the entire stack trace for the error from your `web.log` file?

**Comment by chromadesign** [comment]
It seems to have fixed itself somehow. When I tried installing it again today, it worked fine!
