### ISSUE TITLE
Migration incompatibility with allowAdminChanges = false

### ISSUE THREAD

**Issue by domstubbs** [ethercreative/simplemap#194]
### Description

I’ve just upgraded from 3.5.2 to 3.6.4.1 and everything went smoothly in dev and staging envs, but our production deployment task failed while running migrations.

> Exception: Changes to the project config are not possible while in read-only mode. (/path/vendor/craftcms/cms/src/services/ProjectConfig.php:354)
> #0 /path/vendor/ether/simplemap/src/migrations/m190723_105637_fix_map_field_column_type.php(52): craft\services\ProjectConfig->set('fields.5f2a0858...', 'text’)

After temporarily enabling admin changes the migration completed the second time around. It looks as though the call to `$pc->set()` was the issue. I’m not sure if this is something that can be addressed at plugin level or if it’s a framework/Craft issue, but I thought it would be worth a mention. 

### Steps to reproduce

1. Run `m190723_105637_fix_map_field_column_type` with `allowAdminChanges => false`

**Comment by Tam** [comment]
This should be fixed in the next release, assuming the update is run first in an environment that allows admin changes.
