### ISSUE TITLE
Map Field Doesn't Appear

### ISSUE THREAD

**Issue by mattrothenberg** [ethercreative/simplemap#196]
### Description
The `Map` field doesn't seem to render anything. It's as if the `<simple-map />` web component isn't rendering at all.

<img width="714" alt="Screen Shot 2019-08-05 at 12 04 57 PM" src="https://user-images.githubusercontent.com/5148596/62478705-b6f5d200-b779-11e9-9ca5-e49807836ebe.png">

I noticed this as soon as I upgraded to Craft 3.2 and added the webperf plugin.

<img width="708" alt="Screen Shot 2019-08-05 at 12 16 37 PM" src="https://user-images.githubusercontent.com/5148596/62479266-0dafdb80-b77b-11e9-8615-0fd14ceef0bd.png">

### Steps to reproduce
1. Go to a entry edit page with a `Map` field type
2. See that the `Map` field type is blank
3. Disable the `webperf` sidebar preview, or disable the `webperf` plugin outright
4. See that the `Map` field appears

### Additional info

- Craft version: 3.2.8
- Maps version: 3.6.4.2
- PHP version: 7.3.7
- Database driver & version: MySQL 5.7.23
- Other Plugins: `webperf`

**Comment by mattrothenberg** [comment]
After a conversation on Discord, this appears to be related to the Webperf plugin.

**Comment by khalwat** [comment]
Webperf author here. I eliminated the `bootstrap` error, it was unrelated to this issue, and doesn't fix the problem.

I use webpack to build the asset bundles for Webperf, and initially I thought it might have been some odd conflict of having more than one VueJS loaded, but that appears to not be the case.

I'm happy to help narrow it down with you folks if you're game!

**Comment by dwhoban** [comment]
@khalwat just setup a new project and got the same issue.  Do you need anything to help close this out?

**Comment by khalwat** [comment]
I do -- I'm not sure what could be causing this. Perhaps you can diagnose on your end? Webperf continues to operate property, it's the Maps field that stops working if Webperf is installed and the sidebar is shown (which loads the Webpack bundles).
