### ISSUE TITLE
Error when upgrading 3.5.2 > 3.6.*

### ISSUE THREAD

**Issue by alexbech** [ethercreative/simplemap#199]
### Description
I'm getting this error when trying to upgrade from 3.5.2 to 3.6.0 (or any 3.6.* version)
```
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_location' in 'field list'...

Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'content.field_location' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_location' in 'field list'
```

Also, running ./craft migrate/all doesn't help.

### Steps to reproduce

1. run `composer update ether/simplemap`
2. refresh the control panel

### Additional info

- Craft version: 3.1.32
- Maps version: 3.5.2
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.26
- Other Plugins:
```
    "aelvan/inlin": "^2.1",   
    "aelvan/stamp": "^2.1",   
    "nystudio107/craft-cookies": "^1.1",
    "craftcms/aws-s3": "^1.0",
    "craftcms/redactor": "^2.1",
    "aelvan/imager": "^2.1",
    "aelvan/preparse-field": "^1.0",
    "verbb/image-resizer": "^2.0",
    "verbb/super-table": "^2.0",
    "nystudio107/craft-minify": "^1.2",
    "mmikkel/child-me": "^1.0",
    "mmikkel/cp-field-inspect": "^1.0",
    "mmikkel/cp-clearcache": "^1.0",
    "mmikkel/retcon": "^2.0",
    "ether/logs": "^3.0",
    "nystudio107/craft-emptycoalesce": "^1.0",
    "mmikkel/cp-field-instructions": "dev-master",
    "sebastianlenz/linkfield": "^1.0",
    "verbb/field-manager": "^2.0",
    "craftcms/feed-me": "^4.1",
    "vaersaagod/seomate": "^1.0"
```

**Comment by Tam** [comment]
@alexbech Can you send a copy of your database to dev@ethercreative.co.uk?

**Comment by alexbech** [comment]
Nope sorry - I don’t have a copy anymore.
I ended up uninstalling the plugin before removing all fields and manually deleting any references in the db.
I then installed the latest version of Maps and re-added my fields. Seems to be working now :-)

**Comment by alexbech** [comment]
No I'm sorry - I don’t have a copy of the _"broken state"_ anymore.

I ended up uninstalling the plugin before removing all fields and manually deleting any references to Simplemap/Maps in the db. 

I then installed the latest version of Maps and re-added my fields. Seems to be working now :-)

**Comment by JustJarethB** [comment]
Hi @Tam I have a similar issue, I was attempting to:
 Updating ether/simplemap (3.4.11 => 3.6.4.3)
and came across the same SQL error. It looks as though the `craft_`field prefix is being ignored, and there is also no `field_location` in the `craft_content` table. Can you suggest how to proceed?
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_location' in 'field list'
```
