### ISSUE TITLE
Search index failed to update

### ISSUE THREAD

**Issue by harispepic** [ethercreative/simplemap#201]
### Description
Hi, I have 1744 search indexes jobs to update but since simplemap isn't longer an element type craft isn't able to finish all jobs.

I always get the error -> Class 'ether\simplemap\elements\Map' not found

### Steps to reproduce
1. Try to execute search index jobs

### Additional info

- Craft version: 3.3.0.1
- Maps version: 3.6.4.3
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26
- Other Plugins:
Contact Form	2.2.5
Contact Form Templates	1.0.1
Element API	2.6.0
Entry Instructions	1.0.5
Expanded Singles	1.0.7
GeoMate	v1.0.6
Investment	1.0.0
Maps	3.6.4.3
Navigation	1.1.13
Queue Manager	1.1.0
Redactor	2.3.3.2
SEO	3.6.2
Super Table	2.2.1
Typogrify	1.1.18
XML Sitemap	1.0.9

**Comment by Tam** [comment]
@harispepic Make sure you have run all the update migrations. If any of those tasks were created before you updated the plugin you can safely cancel them, either by using the [Queue Manager](https://plugins.craftcms.com/queue-manager) plugin or by deleting their rows from the `queue` table in your database.

**Comment by harispepic** [comment]
@Tam Thanks, it worked for me!
