### ISSUE TITLE
Search field vs. full address field

### ISSUE THREAD

**Issue by missmatsuko** [ethercreative/simplemap#204]
### Description
I think the "search" field and "full address" fields can be confused for each other due to the layout of the field. 

Maybe the search field should have a label like the rest of the fields, and the map look more like a sub-item of the search field? [Rough mockup](https://user-images.githubusercontent.com/17884198/64211331-b4f75f80-ce5a-11e9-9c5a-1ebf6e96ef18.png)

Also I think it'd be better if the "full address" field were editable without clearing all the fields. We're using search to set the pin location and prefill the address fields, but they often need to be modified to display on the front-end with some more details.

**Comment by Tam** [comment]
Improved in 3.7.0
