### ISSUE TITLE
[FR] Support lat,long pair in CraftQL Query 

### ISSUE THREAD

**Issue by paradigm314** [ethercreative/simplemap#205]
## Description

At the moment searching entries using CraftQL only supports passing an address for location like so:

```graphql
entries(myMapField: $mapSearch) {
   ...on MyEntryType {
    myMapField {
       	lat
        lng
        distance
        parts {
          address
          city
          state
          postcode
          country
        }
     }
  } 
}
# Variables
{
  "mapSearch": {
    "location": "Maidstone, Kent",
    "country": "GB",
    "radius": 100,
    "unit": "mi"
  }
}
```

Unfortunately this doesn't support the, in my opinion, more common use case of searching by lat and long which the ElementQuery does support.

## Possible Solutions
Since GraphQL doesn't support union types for InputTypes yet and the `MapQuery` InputType has location as a String I see two potential solutions. 

### Parse $location as JSON String
To keep the API the same, if the `$location` property is a string in `_searchLocation` it could be  test parsed as JSON and checked for `lat` and `lng` values and treated as an address if parsing fails.  This would allow "{ 'lat': 51.27219908, 'lng': 0.51545620 }" to be passed as a string value to $location and succeed. 

### API Refactor
This would require adjusting the API but would result in better type support.  The `MapQuery` InputType would support both `address` and `location` where `location` accepts lat and long values like so:
```graphQL
input MapQuery {
  address: String
  location:  CoordinatePair
  country: String
  radius: Float
  unit:  UnitEnum
}

input CoordinatePair {
  lat: Float!
  lng: Float!
}
```
If both values are provided location would take precedence. 
To implement this API however the Element API itself would have to break which I don't know if its worth the benefit of getting static typing. 
```php
{% set entries = craft.entries.myMapField({
    address: 'Maidstone, Kent',
    location: { 'lat': 51.27219908, 'lng': 0.51545620 },
    country: 'GB',
    radius: 100,
    unit: 'mi'
}).orderBy('distance').all() %}
```

I would be happy to submit a PR for adding this functionality  I just wanted to get the maintainers opinions on strategy.

**Comment by paradigm314** [comment]
@Tam Awesome solution! 👍

**Comment by stephanedemotte** [comment]
hello (graphql newbie here)

How can i sort my entry by lat long coordinate ?

```
{
   entries(section: "grocery",  type: "saleSpecialist") 
  {
      title
    	... on grocery_saleSpecialist_Entry {
          groceryMap  {
            lat,
            lng
          }
    	}
    }
}
```

I can fetch but don't understant how i can sort by lat long, and find any information in the doc about graphql support.

Any idea ?
