### ISSUE TITLE
Simplemap and Neo

### ISSUE THREAD

**Issue by JoshAinsworth** [ethercreative/simplemap#21]
Hi,

I've come across a minor edge-case bug when dealing with neo and simplemaps. If you have a simplemaps field that is both on an entry and inside a neo field on the same entry, the first field fails to load the google map whilst the one inside the neo field is fine... If that makes sense.

**Comment by dreamseeker** [comment]
Hi,

I had the same problem in neo of the entry editing form.
It seems to be a cause that SimpleMap cannot acquire hideMap's right value in both SimpleMap_MapFieldType.php and map-fieldtype.twig.

**Comment by Tam** [comment]
This should be fixed in v1.5.0.
