### ISSUE TITLE
Frontend embed not automatically assigning centre value

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/simplemap#215]
```
{{ map.embed({
    id: 'map',
    markers: [{}],
}) }}
```

The above embed, when used to output the value of a map field, throws an error
`Map center is missing!`

**Comment by alexjcollins** [comment]
@ChristopherDosin you can track the issue here. 👍

**Comment by ChristopherDosin** [comment]
If you're using `center: map.address` you're also getting the following console error
```
InvalidValueError: setCenter: not a LatLng or LatLngLiteral with finite coordinates: in property lat: not a number
```
<img width="432" alt="Bildschirmfoto 2019-10-24 um 17 22 41" src="https://user-images.githubusercontent.com/8193345/67495084-00700200-f683-11e9-8180-0082ea8b3210.png">
