### ISSUE TITLE
Mapbox forbidden

### ISSUE THREAD

**Issue by alexjcollins** [ethercreative/simplemap#218]
### Description
Via email support:
> I am using the plugin in conjunction with Mapbox and Vue js. I am able to get maps to render on the front end with no problem, so I have a working API key for Mapbox, however, I cannot seem to use it with the GeoCoder.
>If I set the GeoCoder to use Mapbox and put in my API key, I get an error when I try to save any locations saying result in a 403 Forbidden response.
> I am thinking that maybe I don’t have a permission set correctly in my Mapbox account, but I’m not sure what it is, so I was hoping you might have some insight. I would definitely prefer to use Mapbox for my Geocoding because I think it may be more accurate/reliable as an option vs. Nominatim.

**Comment by billymedia** [comment]
I appreciate this has been closed, but i am encountering the exact same issue. When i enter an address into the full address field then save, i get a 403 forbidden error. The api key works fine as i have it working with the plugin in other areas of the site, and the search field works fine, its when i might know the address so add it to the full address field where it throws the 403 error. Any ideas?

**Comment by bengreenbank** [comment]
Hi. We're also experiencing this error after switching our geocoding service from Google Maps to Mapbox. Weirdly, if I enter the URL from the GET request into my browser, then I can see the data fine. (once I have disabled URL restrictions)

**Comment by alexjcollins** [comment]
Hi Ben, we'll take a look over the next few days and report back. Thanks

**Comment by bengreenbank** [comment]
Thanks, I can provide additional details if required.

**Comment by mattsbanner** [comment]
Removing URL restrictions fixed some 403 errors we were receiving (although this does seem to take some time to propagate at Mapbox).

This is not something I have tested by adjusting the Simplemap code, but I wonder if the `Referrer` header needs to be set manually as per point 3 on their [troubleshooting guide](https://docs.mapbox.com/accounts/guides/tokens/#troubleshooting-url-restrictions) since these are server side requests.

**Comment by Saboteur777** [comment]
I also experience this issue.

**Comment by Saboteur777** [comment]
Following the comment of @mattsbanner , I have added the referrer header and it fixed the issue for me.
