### ISSUE TITLE
Importing to a Simplemap field...

### ISSUE THREAD

**Issue by shornuk** [ethercreative/simplemap#22]
Hi, 

Love this map fieldtype, it's super useful enabling the outputting of `parts`.
I'm currently attempting to import a load of entries that contain lat/lng data into a Simplemap field using the Feedme plugin. 

If I import that following :
`{"lat":"{latitude}","lng":"{longitude}","zoom":"14","address":"", "parts":""}`
I get the lat/lng imported into the Simple map field, the marker shows in the correct location, however, the address & parts are left blank. Is there anyway to make Simplemap update these values once it's gotten the lat/lng passed through to it?

Realise it's a long shot, but would love to get this working! Thanks!

**Comment by Tam** [comment]
We've added FeedMe 2 support in v1.5.0. We've also improved the way we populate the address & parts data, so you should be able to import as you would any other field.
