### ISSUE TITLE
Static map image generation not functioning properly

### ISSUE THREAD

**Issue by alinistrate** [ethercreative/simplemap#225]
### Description
- When trying to generate a static image map with markers I am getting an error. 
- We commented out the marker part and when trying to generate the static image there is white background not really the map.

### Steps to reproduce

1. Just include the static embed anywhere and you will see that is not functioning properly...

### Additional info

- Craft version: latest
- Maps version: latest (3.7.2)
- PHP version: 7.3

**Comment by Tam** [comment]
Can you share the stacktrace of the error?
