### ISSUE TITLE
Using SimpleMap Lite in Craft Pro

### ISSUE THREAD

**Issue by vandres** [ethercreative/simplemap#229]
### Description

I don't know if this is a SimpleMap issue and I am sorry if this is more like a support ticket. I recently updated one of my installations to Craft Pro where SimpleMap was installed. Now the Backend is complaining, that I need to buy a license for SimpleMap Pro, but I just want to use the Lite version. How can I enforce the Lite Version?

**Comment by alexjcollins** [comment]
@vandres It should be as simple as going to the Maps listing on the plugin store from within your site, scrolling to the bottom and clicking `Install` on the Lite Version.

<img width="1075" alt="Screenshot 2019-12-12 at 21 38 12" src="https://user-images.githubusercontent.com/12031196/70751142-b4a71400-1d27-11ea-84b1-6d385d5dffaf.png">

**Comment by vandres** [comment]
Thank you very much!
