### ISSUE TITLE
[FR] what3words integration

### ISSUE THREAD

**Issue by ghost** [ethercreative/simplemap#236]
### Description

We'd like to be able to set the location using a what3words address, and likewise be able to geocode existing entries to output the 3 word address in a template. Would it be possible to add this as an optional integration, with an extra setting for API credentials?

For example, if enabled the field would have an extra input that accepts a 3 word address (with or without the /// prefix) which retrieves the Lat/Lng, or finds the address when the pin is located. If this had to be on Save then that'd be fine.

![what3words](https://user-images.githubusercontent.com/49522128/73357182-c1f66e80-4293-11ea-8ae3-a65958c124a1.jpg)

The API details are at:
https://developer.what3words.com/public-api

Many thanks,
Ant

**Comment by alexjcollins** [comment]
Hi Ant, this is a great idea and something we'll definitely discuss!

Would you prefer a dedicated field, or would you be happy with the search field returning w3w locations (if enabled in the plugin config, of course)?

It might also be interesting to include support for Auto Suggest, to catch typos https://developer.what3words.com/public-api/docs#autosuggest

**Comment by ghost** [comment]
Thanks for looking at this, it'd be awesome if you could do some work on it.

As long as there's a field where a user can paste or type the 3 word address then that'd be fine. Auto suggest would be really helpful here too.

When outputting the location on the front-end I'd like the w3w address to be included in the field data so it can be displayed without an extra API lookup.

Please let me know if you need any more info. Thanks again, Ant

**Comment by ghost** [comment]
Thank you so much for implementing this. It works perfectly.
