### ISSUE TITLE
Dragging the map marker around does not update lat/lng

### ISSUE THREAD

**Issue by tsawitzki** [ethercreative/simplemap#237]
### Description

Dragging the marker on the map while editing an entry with a Map field does not update the lat/lng coordinates of the entry – it sticks with the address entered before.
I need updated ltn/lng coordinates as the simple street address is not sufficient or detailed enough in some use cases. 
Wether I use OpenStreetMaps or Google Maps does not matter, it happens in both cases.
I have a fresh Google API key for all required APIs (it’s not stale as in issue #191)

### Steps to reproduce

1. Go to entry with Map field
2. Enter a location, poi or address to get rough location
3. Drag map marker in an attempt to make location more precise
4. Drop map marker at desired location
5. Lng/Ltd field will not update
– 5.1 Save and reload entry
– 5.2 Location will still be the location chosen in 2.

### Additional info

- Craft version: Craft Solo 3.4.5
- Maps version: Lite 3.7.7
- PHP version: 7.0.32
- Database driver & version: MySQL 5.7.23
- Other Plugins: Super Table

**Comment by Tam** [comment]
@tsawitzki I can't re-create this. Are you getting any JS console errors or network errors?

**Comment by tsawitzki** [comment]
The problem was the PHP version. Solved by upgrading to PHP 7.2
