### ISSUE TITLE
No Multilanguage?

### ISSUE THREAD

**Issue by kaspar-allenbach** [ethercreative/simplemap#24]
I just saw that on a multilanguage site the locality is not displayed on the secondary language.

That's the code:
```
{% for loc in entry.gigLocation %}
   {{ loc.title }}
   {% if loc.location.parts.locality is defined %}
      {{ loc.location.parts.locality }}
   {% endif %}
{% endfor %}
```

Primary language `German` prints: 

> Dampfzentrale Bern

Secondary language `English` prints: 

> Dampfzentrale

Why is that? Ist that a bug? The locality should be language independent I think.

**Comment by Tam** [comment]
This should be fixed in v1.5.0.
