### ISSUE TITLE
adding adres via google search

### ISSUE THREAD

**Issue by SophietjesCode** [ethercreative/simplemap#240]
### Description
If you add an address by searching on a company name and then selecting the business from the suggestions in the application the fields: number, streetadress and postcode aren't correctly saved. 

Number isn't added
Streetadress: there the town is added in the same entry
Postcode: isn't added

### Steps to reproduce

1. search for a business
2. select one from suggested dropdowns
3. Save data
4. Data in full adress not complete

https://pasteboard.co/IVI47XA.png

### Additional info

Craft version: 3.4.7
Maps version: 7.3
PHP version:"ether/simplemap": "3.7.7"

**Comment by SophietjesCode** [comment]
The way to get around this bug is to add by hand the data afterwards in the full address field and seperate them by comma.

**Comment by Tam** [comment]
Closing this as Maps currently doesn't support business names in addresses (since only Google really has this kind of data).
