### ISSUE TITLE
Craft 2 SimpleMap field not migrated in matrix block

### ISSUE THREAD

**Issue by jamesmacwhite** [ethercreative/simplemap#243]
### Description

Testing a Craft 2 to Craft 3.4 migration, the SimpleMap plugin installs and runs it's migrations without any issues, but it seems the migration doesn't handle Craft 2 Simple Map fields within a matrix block.

As a specific project example, I have a matrix field called body, within body is a map block and then within that block is a SimpleMap field. This doesn't appear to be picked up to be migrated.

It's not that big of a deal, as I can write a content migration to update it, but just wanted to highlight it, if it's something that can handled within the plugin directly.

### Additional info

- Craft version: 3.4.9
- Maps version: 3.8.1
- PHP version: 7.3
- Database driver & version: MySQL

**Comment by alexjcollins** [comment]
@jamesmacwhite Thanks for letting us know. I'll chat with the team but I would say it's unlikely we'll be doing further work on 2 → 3.x migrations at this stage.

**Comment by jamesmacwhite** [comment]
@alexjcollins No worries. I can write a content migration for our specific project, so not a deal breaker, but just thought I'd highlight it for reference.

**Comment by JustJarethB** [comment]
I also have just run across migration issues. 
    "craftcms/cms": "3.1.15",
    "ether/simplemap": "3.3.5",
@jamesmacwhite would you be willing to share your migration code?

**Comment by jamesmacwhite** [comment]
@JustJarethB Haven't looked into it in much detail yet, but I think it's because the Craft 2 upgrade migration isn't likely returning the matrix field in it's query performed here:

https://github.com/ethercreative/simplemap/blob/v3/src/migrations/m190226_143809_craft3_upgrade.php#L103-L143

I'll do some tests.

Edit: The query is picking up the matrix field, but it's not updating the type. More testing required.

**Comment by jamesmacwhite** [comment]
It looks like the saving of the matrix field returns false, so there is likely an error with the field saving that's silently failing, because saveField() is called without any direct check on if it was successful, it's not picked up in the migration.

**Comment by jamesmacwhite** [comment]
A while later. It is because I don't believe you can migrate matrix fields through the field service, the error likely occurring is due to a duplicate handle error if you dump out the contents of getErrors(). Matrix fields need to modified differently I believe. The core migration does find the matrix field with an old map type but the save field call fails, however it isn't obvious as no check is done if the field save was successful or not and continues on as no exception is raised.

You will have to migrate a old SimpleMap_Map field in a matrix field differently. I assume rather than using the standard fields service, you'd have to do it with the Matrix field service instead.

**Comment by jamesmacwhite** [comment]
I found the issue. it's due to there being a map field that has the same handle in both a global and matrix context, I believe this is technically OK, given it's two different contexts, but as the migration uses field contexts and saveField to init the new map field, it encounters a duplicate handle when saving. The simplest solution is rename the matrix field handle to something else,
