### ISSUE TITLE
[Question] Sort by lat long, distance in graphql

### ISSUE THREAD

**Issue by stephanedemotte** [ethercreative/simplemap#246]
hello (graphql newbie here)

How can i sort my entry by lat long coordinate ?

```
{
   entries(section: "grocery",  type: "saleSpecialist") 
  {
      title
    	... on grocery_saleSpecialist_Entry {
          groceryMap  {
            lat,
            lng
          }
    	}
    }
}
```

I can fetch but don't understand how i can sort by lat long, and i don't find any information in the doc about graphql support.

Any idea ?

Thanks !

**Comment by Tam** [comment]
We've just added rudimentary support for searching via the map field in GraphQL which means it's now possible to search by distance.

See the docs for more: https://docs.ethercreative.co.uk/maps/how-to/graphql/
