### ISSUE TITLE
Add MapQuery Type to GraphQL

### ISSUE THREAD

**Issue by TomDeSmet** [ethercreative/simplemap#248]
I'd like to be able to query my entries by an address and a radius through the built-in GraphQL API. But it seems the MapQuery Type is missing which exists in the CraftQL API.

Could this be implemented, please?

**Comment by Tam** [comment]
Currently Craft doesn't allow plugins to add their own custom argument types like the CraftQL plugin does. To work around this we've added support for stringified JSON to be passed that will allow you to search by the map field. 

See the docs for more: https://docs.ethercreative.co.uk/maps/how-to/graphql/
