### ISSUE TITLE
Street View support

### ISSUE THREAD

**Issue by tomkiss** [ethercreative/simplemap#250]
### Description

Feature request! In my use case it's exceptionally helpful to be able to access Google streetview inside the control panel form. I can see why its been disabled, due to the (very nice) custom UI overlay being used. Perhaps a modal could be used to load the streetview via a separate map?

### Steps to reproduce

1. Load the Simple Map field in a CP entry with Google Maps.
2. Observe that there is no streetview control (normally on by default).

### Additional info

- Craft version: 3.4.15
- Maps version: 3.8.2

**Comment by Tam** [comment]
Sorry, this isn't something we'll be supporting. This is partly due to it being too specific to a single mapping library and partly due to technical limitations.
