### ISSUE TITLE
Database Exception when re-saving asset volume

### ISSUE THREAD

**Issue by daltonrooney** [ethercreative/simplemap#251]
### Description
I'm not sure exactly what Craft is doing in the background when I re-save an assset volume, but I'm getting stuck on a Database Exception related to a Maps field.

```
Database Exception – yii\db\Exception
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_map' at row 377
The SQL being executed was: ALTER TABLE `content` CHANGE `field_map` `field_map` varchar(255)
Error Info: Array
(
    [0] => 22001
    [1] => 1406
    [2] => Data too long for column 'field_map' at row 377
)
```

The contents of that field is something like this:

`{"id":null,"ownerId":"1018","ownerSiteId":"1","fieldId":"38","lat":"32.731283900","lng":"-117.151090800","zoom":"15","address":"San Diego Art Institute, El Prado, San Diego, CA, USA","parts":{"number":"1439","address":"El Prado, Balboa Park","city":"San Diego","postcode":"92101","county":"San Diego County","state":"California","country":"United States"},"distance":null}`

Which is definitely more than 255 characters. I checked a couple of other entries with map fields and they were of a similar length.

### Steps to reproduce

1. Re-save any assets volume.

### Additional info

- Craft version: 3.4.15
- Maps version: 3.8.3
- PHP version: 7.3.14
- Database driver & version: MySQL 5.7.29

**Comment by Tam** [comment]
@daltonrooney It looks like Craft is trying to change the type of the database column. It's hard to say why it's doing this without more info. Could you share the full stacktrace leading up to that error?

**Comment by daltonrooney** [comment]
Sure, thanks for taking a look, [here's the stacktrace](https://gist.githubusercontent.com/daltonrooney/beb4511dd7a2fbdef63af6af22456076/raw/4076b7b577ecd20bd3c1aa919d2a198e3f748971/stacktrace). 

I found that setting `'useProjectConfigFile' => false` in my Craft general.php allows the volume to re-save, so this is probably not a problem with the Maps plugin after all. I'm reporting to the Craft team, so I'll close this out for now.

**Comment by alexjcollins** [comment]
Thanks for the update here 👍
