### ISSUE TITLE
How to get all entries but still order by distance

### ISSUE THREAD

**Issue by max8hine** [ethercreative/simplemap#252]
### Description

```
{% set entries = craft.entries.myMapField({
    location: { lat: 51.272154, lng: 0.514951 },
}).orderBy('distance').all() %}
```

Above query will get entries that coordinate within 50 kilometres due to the `radius` restriction.

Is there any way to get all entries but ordered by distance, without the `radius` restriction?

Thanks

### Additional info

- Craft version: 3.4.11
- Maps version: 3.8.2

**Comment by Tam** [comment]
@max8hine You can just set the radius to something that will catch all locations. For example, the radius of Earth:

```twig
{% set entries = craft.entries.myMapField({
    location: { lat: 51.272154, lng: 0.514951 },
    radius: 6371,
}).orderBy('distance').all() %}
```
