### ISSUE TITLE
Update from maps from 3.5.2 to anything newer results in "Column not found" error. 

### ISSUE THREAD

**Issue by outline4** [ethercreative/simplemap#253]
I am on Craft CMS 3.4.x and I try to upgrade Maps from 3.5.2 to anything newer via Composer update.   
But it always fails. 

I know that I could run ./craft migrate/all - BUT on this particular project I cannot do this. 

Is there another way of fixing this? 

The error I get is "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_cf_project_map' in 'field list'"

I have only two maps fields and none within a matrix or so. 

- PHP version: 7.2

Any help appreciated!

**Comment by Tam** [comment]
@outline4 That error suggests that a field with the handle `cf_project_map` existed at some point, but was deleted. Probably the easiest workaround is to re-create that field, then try to upgrade Maps.

**Comment by outline4** [comment]
Hi,  
The field is still there. But: it’s not used anywhere.  

What should I do?  
Add this field to a section and add a dummy entry?  

Cheers  
Stefan

**Comment by outline4** [comment]
So I went ahead and added a new section dummy with the field in question. 
When I try to add an entry it generates an error: 

PHP Notice – yii\base\ErrorException
Trying to get property 'postcode' of non-object

More: 

	•  in /home/httpd/vhosts/.../vendor/ether/simplemap/src/services/MapService.phpat line  352
343344345346347348349350351352353354355356357358359360361    
/**
     * Populates any missing location data
     *
     *
 @param
 MapRecord $record
     *
     *
 @throws
 \yii\db\Exception
     */

    
private function _populateMissingData (MapRecord $record)

    {

        
$postcode = is_array($record->parts) ? $record->parts['postcode'] : $record
->parts->postcode;
 
        
// Missing Lat / Lng

        
if (!($record->lat && $record->lng) && ($record->address || $postcode
))
        {
            
$latLng = GeoService::latLngFromAddress($record->address ?: $postcode
);
            
$record->lat = $latLng['lat'
];
            
$record->lng = $latLng['lng'
];
        }
 

What does that mean? 

Stefan

**Comment by outline4** [comment]
So after recreation of the field in the dummy section I went ahead and tried to update from 3.5.2. to 3.8.3.

This time it resulted in almost the same error, BUT with another maps field (field_cf_project_maps).
This field IS in a section and well displayed. 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'content.field_cf_project_maps' in 'field list‘
NOTE: the only difference in the name is the „s“ map vs. maps. 

This thing is really hard to update. 

Is there anything you would recommend? 

I can’t delete the field and start from scratch, because there are 100s of entries…
And the same thing goes for this field: If I try to save an entry within this section, it’ll generate this error: 

PHP Notice – yii\base\ErrorException
Trying to get property 'postcode' of non-object

Cheers
Stefan

**Comment by outline4** [comment]
OK,  
I managed to get this working. 

I must say, it wouldn't be possible without the access to composer and ./craft migrate/all.  
Turns out, that the guy who was prepping the project forgot to copy the craft.bat file.  
That resulted in all sorts of bad behavior... 

Still: maps has been notoriously hard to upgrade. But with your advice on running migrations manually it wasn't actually THAT bad.
