### ISSUE TITLE
Geographical Location Changes After Search and Click

### ISSUE THREAD

**Issue by benjaminkohl** [ethercreative/simplemap#26]
I am using the field type to select one of the Virgin Islands because the entire island needs to be displayed on the map. Once I select the geographical location from the dropdown, I see the pin appear on the map but the value in the text field changes to "Unnamed Road, British Virgin Islands". I didn't select a road so I don't know why this happens.

If I save the entry and return to the edit form later, I see the map is on a different island with the pin on that "unnamed road". Is the map widget in the control panel only limited to saving road locations?

**Comment by benjaminkohl** [comment]
I have another request. Can you set "scrollwheel" option to _false_ (or add a config variable that allows this) for the map display in the control panel? It is too easy to accidentally screw up our maps as we scroll through an entry's edit form.

**Comment by masuga** [comment]
Unfortunately, these couple issues are making this plugin unusable.

**Comment by Tam** [comment]
These should be fixed in v1.5.0.
