### ISSUE TITLE
Error with what3words integration

### ISSUE THREAD

**Issue by tomkiss** [ethercreative/simplemap#291]
### Description

Hey there, I'm encountering an error with the what3words integration with the PRO license.

### Steps to reproduce

I'm not entirely sure of the steps, but it's come about from disabling and enabling the what3words setting in the control panel.

1. Turn on what3words integration, add API key etc.
2. Edit an entry with a maps field
3. Turn off what3words integration
4. Try to edit the entry
5. Turn on what3words integration
6. Maybe repeat?

At some point when trying to edit the entry, I'll get a 500 error and the log will say:

```
2021-01-27 18:41:52 [-][1][p304hse8oou5rh2ds6qda2t0ml][error][yii\base\ErrorException:8] yii\base\ErrorException: Trying to access array offset on value of type bool in .../vendor/ether/simplemap/src/services/What3WordsService.php:25
```

### Additional info

- Craft version: 3.6.1
- Maps version: 3.9.0.2
- PHP version: 7.4.2
- Database driver & version: MySql
- Other Plugins: SEOmatic, Retour

**Comment by shornuk** [comment]
Same here, in testing, I'm thinking it might be a php 7.4 compatibility thing? Only happened since we recently installed 7.4.

**Comment by tomkiss** [comment]
Hmmm, this was occurring for me on, er, 7.2.4 so pretty sure it's not related.

I added `?? false` to the end of What3WordsService.php line 25 and it fixed it. But tbh I don't know the actual nature of the problem so wasn't going to submit a PR, am a little blind.

**Comment by samhibberd** [comment]
> Hmmm, this was occurring for me on, er, 7.2.4 so pretty sure it's not related.

@tomkiss be good to clarify this, the original issue report suggests you are using 7.4.2? 

Also for reference Craft 3.6 requires at least PHP 7.2.5: https://craftcms.com/knowledge-base/upgrading-to-craft-3-6#php-7-2 not sure if that is related at all.

**Comment by tomkiss** [comment]
@samhibberd Oh dear. Apologies! I'm confusing myself now. Had to double check...

I was running 7.4.2 locally via MAMP and 7.2 on my production server (yes, different versions, this is super sloppy I know). After Craft 3.6 came out I upgraded my production server, which is now 7.4.14 - but I've seen the issue on both versions of PHP.

**Comment by tomkiss** [comment]
OK, FWIW I've created a pull request. 

Like I say, I don't really understand the underlying issue but it seems like there's a lot on the plate in this repo, even for paid users so hopefully, this is helpful.

**Comment by tomkiss** [comment]
@samhibberd if you have a mo to check that PR and consider merging that would be much appreciated.

**Comment by tomkiss** [comment]
@samhibberd I understand you guys a no doubt busy, but as a paid product, it would be nice to have any sort of update on the issue or whether that PR is welcome. Currently having to edit the source file whenever I deploy to production.

🙏 Muchas gracias

**Comment by samhibberd** [comment]
Sorry @tomkiss I'm just a fellow developer,  not my plugin :)

**Comment by tomkiss** [comment]
OMG! I am so sorry @samhibberd. 
Looking at the thread, I don't even know where I got the idea you were the owner!!!! 😵 Think I'm going mad...

**Comment by tomkiss** [comment]
Hi @Tam and team - Is there any chance you could please check out the PR I've made for this issue. I'm not quite clear on the underlying root cause. I'm a paid user so it would be nice to have any sort of update. Currently having to edit the source file whenever I deploy to production.

🙏 Muchas gracias

**Comment by tomkiss** [comment]
Hey, so is there any news on this?

Glad to see there was another fix and a version bump recently for something else. Can someone please review this super simple change in the PR request?

**Comment by tomkiss** [comment]
Hi @alexjcollins @Tam and team - is there any update on this?

Please can you review my pull request to fix this error. It's such a small change! I don't want to publish a fork for such a small issue but at the moment I'm editing `/ether/simplemap/src/services/What3WordsService.php` on each production deployment to stop the site crashing.

Kind of frustrating for a paid plugin. What's going on with this plugin is it vapourware now?

**Comment by shornuk** [comment]
Sad to see no update on this. Could understand for a free plugin, but w3w is part of the paid version. I imagine it'll be marked as 'Abandoned' in the plugin store soon so at least that will ward people off.

**Comment by alexjcollins** [comment]
@tomkiss Thank you very much for your PR, we've included it in the latest release.

**Comment by tomkiss** [comment]
@alexjcollins Thank you SO much for this 🙌
