### ISSUE TITLE
Trial time length

### ISSUE THREAD

**Issue by yahm23** [ethercreative/simplemap#292]
### Description

This isn't an issue for a report, but a general enquiry. I didn't know where else to write/message.

I'm implementing this package in a Craft CMS site for a technical test for a role I'm applying for, and it works great. 
I 'activated' my trial account today, and was wondering how long would I have access to this? I have to present my work this coming Tuesday, will that be long enough for the trial features to still work?

Many Thanks

**Comment by alexjcollins** [comment]
Hi @yahm23
Craft only requires you to purchase a license once you take your site to production. So if this is just for a technical test that's not going live, you'll have as long as you need. Good luck with the job application.

Thanks, Alex

P.S. If we're also hiring a [frontend Craft Developer](https://ethercreative.co.uk/careers/frontend-developer)

**Comment by yahm23** [comment]
Thank you @alexjcollins! 
I'll check it out!
