### ISSUE TITLE
Submitting to Simplemap from Front End form

### ISSUE THREAD

**Issue by shornuk** [ethercreative/simplemap#30]
I currently have a front end form that is passing lat/lng values to Simplemap. The only issue is that when I save this, it only captures the lat and long and therefore the address and parts are not generated. Any idea if it would be possible to achieve this? I'm thinking it would work similar to Josh's Feedme integration that completes the rest of the data from the supplied lat/lng, presumably after save?

Really like this plugin so would be great if this can be achieved! Thanks.

**Comment by Tam** [comment]
This should be fixed in v1.5.0.

**Comment by shornuk** [comment]
Awesome! Thanks.

**Comment by shornuk** [comment]
Am I right in thinking that this behaviour is gone from the C3 latest version? Again, submitting to a front end form and passing the lat/lng only saves those values, and doesn't complete the rest.
