### ISSUE TITLE
Dynamic Map Not Filling Container

### ISSUE THREAD

**Issue by kerns** [ethercreative/simplemap#303]
I am rendering a dynamic map inside of a container, where I would expect the map to fill the width and height of the parent container. It is defaulting to 640 x 480 instead – what am I missing?

<img width="1248" alt="Screen Shot 2021-04-19 at 09 55 54" src="https://user-images.githubusercontent.com/20254/115201595-c9eb3a00-a0f5-11eb-8b03-890bfbfd82b5.png">

```
{{ newaddress.embed({
  options: {
    disableDefaultUI: true,
    draggable: true,
  },
})|attr({class: ''}) }}

```

Any hint would be appreciated.

**Comment by Tam** [comment]
You'll probably want to pass `width: null, height: null` to the options, then style the map to fit the bounds as needed.

**Comment by kerns** [comment]
Thanks  @Tam – but I can't find a single example of needing to this in the simple map docs, or as an option in Google's docs. It's weird because it's the logical default case, right – I mean if you're embedding a map, you want it to fill the full height and the full width of the parent or target container, right?

And it also looks like all of the code simple maps generates has width:100% and height:100% applied, again, as one would expect. Needing to specify null seems like some edge case remedy, not a default strategy. Where is it getting this value for 640x480?

Anyway – I still tried as you suggested but no change. Anything else I should look into? 🤔

**Comment by kerns** [comment]
I've tried everything I can think to try, ~~twice~~ thrice. Can you share an example you know is working of a full container width/height dynamic/embedded map using the latest version of your plugin?
