### ISSUE TITLE
Field: map not displayed 403 

### ISSUE THREAD

**Issue by palomamtnez** [ethercreative/simplemap#307]
### Description

Is it normal to have the map field shown like this?
I mean, the map images are not loading and I get a 403 from https://maps.wikimedia.org/

![Screen Shot 2021-04-30 at 10 49 14 AM](https://user-images.githubusercontent.com/13962572/116628003-53c2bf00-a9a2-11eb-9034-f8331011a0da.png)

I just installed it (version 3.9.0.2), didn't configure anything special, I am using the default provider: Nominatim 

Any help Is appreciated 
Thanks

![Screen Shot 2021-04-30 at 10 53 22 AM](https://user-images.githubusercontent.com/13962572/116627988-4d344780-a9a2-11eb-8d12-07733550ccc5.png)

### Additional info

- Craft version: Craft CMS 3.6.12.1
- Maps version: 3.9.0.2
- PHP version: 7.3.27
- Database driver & version: MySQL 5.5.5
- Other Plugins:

**Comment by ghost** [comment]
We have the same problem.
