### ISSUE TITLE
Ability to save field with marker anywhere

### ISSUE THREAD

**Issue by engram-design** [ethercreative/simplemap#322]
In our scenario, we're primarily using this plugin for longitude/latitude points, to plot on a globe. We don't overly care about the address (although it's handy to zoom into the area to place the marker).

However placing the marker in the CP anywhere that isn't a valid address causes the marker to not save. For example, adding a marker in the middle of the ocean won't save.

We've tried enabling the longitude/latitude fields for the Map field, entering an address, then moving the marker to the ocean, removing the address (but there's still valid values for longitude/latitude and hitting save, but it always reverts back.

**Comment by alexjcollins** [comment]
Thanks for flagging Josh, we'll investigate 🕵️‍♂️

**Comment by engram-design** [comment]
Thanks @alexjcollins will let you know if any issues!

**Comment by engram-design** [comment]
Sorry to bring this up again, but seeing some weird behaviour with this. If I'm dropping the marker out to sea, it seems to work well, but closer to land it doesnt?

I've put a little video together, where you can see the long/lat values update if pushing  out to sea a bit more.


https://user-images.githubusercontent.com/1221575/131428104-8cf1cc22-aa2f-41f2-9432-848e5f4da144.mp4

**Comment by engram-design** [comment]
Any further thoughts on this one @jamesedmonston @Tam ?
