### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by itsmattsoria** [ethercreative/simplemap#328]
The full documentation page linked to from the README is missing: https://docs.ethercreative.co.uk/maps

Actually it looks like all of your docs on https://docs.ethercreative.co.uk/ are missing

**Comment by alexjcollins** [comment]
Thanks @itsmattsoria — Maps docs should be fixed

**Comment by itsmattsoria** [comment]
Awesome, thank you!

**Comment by ademers** [comment]
This appears to be an issue again. Getting _Page not found_ for the Maps docs and others I've tried. https://cln.sh/kwY5rDKSDwD9Tw8Ihxq8

**Comment by alexjcollins** [comment]
Strange! It's working ok for me. 

![Screenshot 2021-12-02 at 06 52 20](https://user-images.githubusercontent.com/12031196/144372578-609814a0-838c-4328-a43d-93849407492b.jpg)

At the momemnt, only Maps and Web Payments have working docs.

**Comment by ademers** [comment]
The Maps docs stated working for me again late afternoon yesterday EST. However, they were not at time I wrote above comment. Others can confirm, so not just me.
