### ISSUE TITLE
Linking to Google Maps?

### ISSUE THREAD

**Issue by gracehcoote** [ethercreative/simplemap#329]
I am hoping this is straightforward, I feel it should be and am probably being thick! But basically, I am using this plugin for venue locations for a site I'm building. The page echoes out the addresses of one or more locations which have been saved in the admin using the map. I then also have a button beside each of these addresses, which I would like to simply open Google Maps in a new tab showing the location. Is this possible?

Thank you in advance!

### Additional info

- Craft version: 3.7.16
- Maps version: Lite 3.9.2
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32
- Other Plugins:

**Comment by alexjcollins** [comment]
Hi @gracehcoote

I would probably have something like this:
`https://www.google.com/maps/search/?api=1&query={{ addressField.address|replace({' ': '+'}) }}`

Which should give you something like:
https://www.google.com/maps/search/?api=1&query=77A+Charterhouse+St,+London+EC1M+6HJ

I think you can also do a similar thing with lat/lng values in the URL params.

Hope that helps!

**Comment by gracehcoote** [comment]
Ah, perfect, thank you so much! I knew it would be simple lol, this works perfectly.
