### ISSUE TITLE
Touch when dragging

### ISSUE THREAD

**Issue by shornuk** [ethercreative/simplemap#33]
Hi. Solid update with 1.5. Thanks! Minor issue, which I'm not sure if it's to do with the plugin or google api.

On mobile, if your swiping down the page and you swipe on the map, you get the "use two finger to move map" message, which is great, but the map still detects the touch and will move the marker to wherever you tapped when you started to swipe. Hope that makes sense!?

**Comment by Tam** [comment]
Fixed in [v1.6.0](https://github.com/ethercreative/simplemap/releases/tag/v1.6.0)

**Comment by shornuk** [comment]
Nice!
