### ISSUE TITLE
Using with Feed Me

### ISSUE THREAD

**Issue by gracehcoote** [ethercreative/simplemap#330]
### Description

I swear I don't normally open so many issues, please bear with me!

I am trying to use the Feed Me plugin [https://docs.craftcms.com/feed-me/v4/](url) to import a list of venues in JSON format into Craft as categories. One of these fields is an address, which is intended to insert into the Full Address field of the Map plugin. Trying to import the feed results in a list of errors for any venues which actually have this field populated (some are blank, these all import fine). So I'm assuming there is an issue with importing to a Map field.

The error I get is a strange one:

`cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://nominatim.openstreetmap.org/reverse?format=jsonv2&limit=1&addressdetails=1&accept-language=en&lat=54.99656096291442&lon=-7.32259728836355 - CurlFactory.php: 211.`

I have also tried using latitude and longitude, with the same result, so again my conclusion is the Map field is what's causing the issue here.

Any ideas at all what might be going on here? Any help would be much appreciated!

### Additional info

- Craft version: 3.7.16
- Maps version: Lite 3.9.2
- PHP version: 7.4.12
- Database driver & version: MySQL 5.7.32
- Other Plugins: Feed Me 4.4.0

**Comment by gracehcoote** [comment]
I'm coming to the conclusion that I need more API keys and that those require money, which I'm not in a position to pay for, so sadly I don't think I can use the plugin for this project. Closing this as a result.

**Comment by alexjcollins** [comment]
@gracehcoote Depending on the number of requests you need to make, I think Google has a pretty decent free allowance for their geocoding API ($200 from memory). From our testing that has been the most reliable option, too.
