### ISSUE TITLE
Documentation URLs 404ing

### ISSUE THREAD

**Issue by robzor** [ethercreative/simplemap#333]
### Description
Hi there, just to let you know i'm getting 404 errors on all the docs pages on docs.ethercreative.co.uk other than the root URL.

### Steps to reproduce

1. Go to https://docs.ethercreative.co.uk/maps

**Comment by alexjcollins** [comment]
Thanks for flagging - our Github token had expired.
Maps, SEO and Web Payments should be working now.

**Comment by fbnntt** [comment]
Have the docs moved to a different URL or does the token need refreshed again?
