### ISSUE TITLE
Mapbox integration within {% cache %} template tags causes "Undefined key 0"  from TemplatesCache.php

### ISSUE THREAD

**Issue by RedLucas** [ethercreative/simplemap#340]
### Description
If an {{ map.embed() }} is run within a {% cache %} tag, it produces the attached error. 

I've actually been able to figure out exactly why and it's EmbedService->_js(). 

if the `$view->registerScript()` were changed to the equivalent `$view->		$view->registerJsFile()`, it would be fixed. The problem is because TemplatesCache.php is expecting there to always be a value, the first parameter of registerScript() cannot be an empty string. (We can talk about if that's also a bug but I digress).

### Steps to reproduce

1. Add Map field with content to an entry.
2. Set up Mapbox integration (though I don't believe this is actually exclusive to Mapbox.
3. Render the map in twig via {{ map.embed() }} within {% cache %} tags. 

<img width="1371" alt="Screen Shot 2022-04-22 at 12 44 34 PM" src="https://user-images.githubusercontent.com/8796324/164783835-fa38560e-1e8b-4016-bcfc-07d3c7ab3a66.png">

**Comment by alexjcollins** [comment]
Thanks Lucas, we'll check this out next week and merge. Enjoy the weekend.

**Comment by RedLucas** [comment]
So while I think this fixes the issue of it just totally erroring out, it creates a separate issue that I'm pretty sure is completely related to a CraftCMS issue. 

Because we're now attaching the JS file properly within a {% cache %} tag, they do not work within a {% cache %} tag. 

We don't have an error, but the JS isn't getting attached. 

I wonder if we could get around this issue by putting just any string into the value of the first parameter of "registerScript()" so that it doesn't error out, but also works aroudn the CraftCMS issue related to the Cache tags and attached JS.

https://github.com/craftcms/cms/discussions/9987

**Comment by RedLucas** [comment]
So it looks like that other issue was fixed in Craft 4, any chances of getting this merged? I'm currently using my own branch but I'd like to get out of that. Let me know.

**Comment by eese-dev** [comment]
I am experiencing this issue on v4.0.8. It appears #341 escaped v4, being merged into v3 in June after v4 development began in May.

<img width="985" height="493" alt="Image" src="https://github.com/user-attachments/assets/2af834a1-cce3-4939-ad49-8cf99b3ea16d" />
