### ISSUE TITLE
Usage from another plugin

### ISSUE THREAD

**Issue by 8cylinder** [ethercreative/simplemap#35]
I'm creating entries programmatically that have a SimpleMaps field.  I have latitude and longitude data and I want to add that to the entry when I create it.

This code doesn't work, but it's basically what I'm trying to do.
```
$entry->setContent([
    'simplemap_field' => [$lat, $long],
    'some_other_field' => 'some text',
]);
```
I'm guessing I need to create a simpleMap object first then add that to my entry.
```
$sm = New SimpleMap([$lat, $long]);
...
    'simplemap_field' => $sm,
...
```

Can you point me toward some documentation covering this?

**Comment by Tam** [comment]
You should be able to do something like:

```php
$entry->setContentFromPost([
    "mapField" => [
        "lat" => 0.43223587,
        "lng" => 0.43223587,
        // or
        "address" => "123 Fake Street",
    ],
]);
```
