### ISSUE TITLE
Can't get  map to display 100% width

### ISSUE THREAD

**Issue by damienbuckley** [ethercreative/simplemap#352]
### Description

Documentation references (see max image sizes below) but there is no further detail and I can't figure out how to apply 100% width

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- Maps version:
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by alexjcollins** [comment]
@damienbuckley Something like this should work:

```
{{ craft.maps.embed({
    id: 'myMap',
    width: '100%',
    height: '700',
 }) }}
```

(This was pulled from production code on one of our projects, using Google Maps)

**Comment by damienbuckley** [comment]
Yeah I had trie3d that but I get a Type Error…

`      {{ entry.map.embed({
          id: 'map',
          width: '100%',
          height: 400,
          zoom: 13,
          markers: [{}],
      }) }}`

Cannot assign string to property ether\simplemap\models\StaticOptions::$width of type int

I'm just setting it with an inline style rule now but would be interested to hear what the issue is.

**Comment by tigerchick** [comment]
I just had the same thing. It's because its expecting an integer number not a string like '100%'.
I hacked it to work by altering line 670 in venderether/simplemap/src/services/EmbedService.php to % instead of px
Obviously that will break if you then update the plugin to a newer version and won't then allow you to use a px value if you need it.

**Comment by alexjcollins** [comment]
Can I ask which PHP versions you are both running?

**Comment by tigerchick** [comment]
Sure, it's 
8.1.8

**Comment by damienbuckley** [comment]
8.0.8

**Comment by CreateSean** [comment]
18 months later and this is still an issue. 

Is there anyway to resolve this without hacking the plugin?

**Comment by DanielDarrenJones** [comment]
For anyone else who bumps into this, here is a workaround which worked for me:
```
{{ myMapField.embed({
    id: ‘map’,
    markers: [{}],
})|attr({
    style: ‘width: 100%;’,
}) }}
```
