### ISSUE TITLE
Default Latitude & Longitude only accepts whole numbers

### ISSUE THREAD

**Issue by CreateSean** [ethercreative/simplemap#36]
In the fieldtype settings the Latitude/longitude options only allow whole numbers. This means the default setting is off a couple hundred kilometers from where I want it to be.

I need: 43.6525 and -79.381667 which is Toronto ON, but if I go with whole numbers I either end up in Niagara Falls (43, -79) or the middle of a farmers field in the middle of nowhere (44, -79).

**Comment by Zae** [comment]
I'm having the same problem, the plugin won't event accept the coords generated by the location service when entering an address.

Is there an easy way to fix this?

**Comment by CreateSean** [comment]
I ended up just using the google api and feeding it a text field with an address. No fancy map in the control panel but works fine on the front end.

**Comment by Tam** [comment]
Whoops, that's fixed in [v1.5.1](https://github.com/ethercreative/simplemap/releases/tag/v1.5.1)

**Comment by Zae** [comment]
@Tam I think that only solves the problem that chrome won't save the decimals, I was getting validation errors from craft because I have the nl_NL locale loaded which uses , instead of . and mysql won't accept that.
