### ISSUE TITLE
Migrate an existing field to match the format of simplemap

### ISSUE THREAD

**Issue by martisj** [ethercreative/simplemap#363]
I have a field called `boulderPosition` that has two sub fields `latitude` and `longitude`, how would you go about migrating these fields to match Simple Maps `lat` & `lng` fields?

**Comment by alexjcollins** [comment]
Hey @martisj 

Are you able to access those sub-fields when exporting using Crafts element exporter? If so, I would simply export them and then, using FeedMe and the entry slug as the unique identifier, reimport all those entries with the `latitude` and `longitude` fields mapped to the equivalent fields in Simple Maps.

I hope that helps!

**Comment by martisj** [comment]
@alexjcollins Phenomenal suggestion! It works on my local machine, however I can't get the Feed Me panel to show up in staging... That has absolutely nothing to do with the Simple Maps plugin so I will not pester you with that 😊 Merry Xmas 🎄

**Comment by alexjcollins** [comment]
Thanks, @martisj  Merry Christmas.
I hope you manage to figure out the Feed Me issue on staging.
