### ISSUE TITLE
Normalize Location error for partial postcode search

### ISSUE THREAD

**Issue by iamtompickering** [ethercreative/simplemap#368]
I seem to be hitting the following error when I try and search with specific postcodes both partial and full e.g. 'WN4' or 'WN4 5DH'. Other postcode variations seem to work absolutely fine. but there seems to be some issue with ones that include 'WN'?! 

Is there any reason why this would be happening? Screenshot of error below. 

![CleanShot 2023-01-17 at 09 54 07](https://user-images.githubusercontent.com/6592882/212867496-e89cf309-8c05-4c56-b117-b60d58145beb.png)

**Comment by Decyphr** [comment]
I also ran into this issue.
 It seems to be thrown when `$location` is a string, but is an invalid GeoService location. 
 
 In this case, line 677 `$location = self::latLngFromAddress($location, $country);` returns null. 

I was able to resolve this by adding a null check to the function: 
public static function normalizeLocation (mixed $location, string $country = null): array
```php
public static function normalizeLocation (mixed $location, string $country = null): array
{
	if (is_string($location))
		$location = self::latLngFromAddress($location, $country);
	else if ($location instanceof Map)
		$location = ['lat' => $location->lat, 'lng' => $location->lng];
	else if (!is_array($location) || !isset($location['lat'], $location['lng']))
		$location = [];

        // added null check for $location
	if (!$location) {
		$location = [];
	}

	return $location;
}
```
