### ISSUE TITLE
[BUG] Mapbox tokens not displayed on save

### ISSUE THREAD

**Issue by Antimated** [ethercreative/simplemap#374]
After I press 'save' when adding my mapbox token, the fields `Map token` and `Geo token` are getting cleared out.

**Comment by alexjcollins** [comment]
@Antimated Thanks for flagging. Are you pasting actual values, or are you using env vars?

**Comment by Antimated** [comment]
> @Antimated Thanks for flagging. Are you pasting actual values, or are you using env vars?

I'm pasting values

**Comment by elliotkidd** [comment]
This is also happening with Google API keys too...

**Comment by elliotkidd** [comment]
> This is also happening with Google API keys too...

Perhaps worth noting its multi site... seems to work as expected prior to converting this project to a multisite setup.
