### ISSUE TITLE
Google API key

### ISSUE THREAD

**Issue by sjadema** [ethercreative/simplemap#38]
Since version 1.5.0, the geocoding is done via a curl. This means previously generated Google API keys with a browser restriction won't work anymore as the request is now a server request opposed to a browser request (when using Javascript).

This should be mentioned in the CHANGELOG as a breaking change since the feedback in the CP is still there (it uses the JS library) but the address parts won't get saved anymore (it uses a server request).

I would also recommend using different API keys for front & CP requests as the key used by SimpleMap has no restrictions on it. It is used for JS and server requests and you can only add 1 restriction per key in the [Developer Console](https://console.developers.google.com).

**Comment by Tam** [comment]
Added an alternative server API key setting in [v1.6.0](https://github.com/ethercreative/simplemap/releases/tag/v1.6.0)

**Comment by sjadema** [comment]
Thanks @Tam!

**Comment by terryupton** [comment]
I have entered both a Alternate Server API Key and Google Maps API Key but it seems that in the backend only the Google Maps API Key is used? Is this a bug or have I misunderstood its use case?

**Comment by Tam** [comment]
@terryupton The alternate API is meant to be used by the server (for searching by location) if you need to put restrictions on the main user facing API key. The main API key is used where ever a map is displayed (and if you use `craft.simpleMap.apiKey`).
