### ISSUE TITLE
Cannot assign null to property ether\simplemap\models\Map::$zoom of type int

### ISSUE THREAD

**Issue by pdaleramirez** [ethercreative/simplemap#381]
I encountered the `$zoom` type error after upgrading from Craft 3 to 4.
Cannot assign null to property ether\simplemap\models\Map::$zoom of type int

For a quick fix, you can add `?` in the Map model.

`public ?int $zoom = 15;`

![Screenshot 2023-11-13 at 7 58 46 AM](https://github.com/ethercreative/simplemap/assets/4172750/97cc8581-30a6-4b85-8599-127e8f5145e5)

**Comment by lukasNo1** [comment]
I have the same problem after updating to craft 4. It only affects the entries where the map field was empty.

For a quick fix i just ran an SQL Query, the null check in the model would be good though.

UPDATE content 
SET field_FIELDNAME = REPLACE(field_FIELDNAME, '"zoom":null', '"zoom":8') 
WHERE field_field_FIELDNAME LIKE '%"zoom":null%';
