### ISSUE TITLE
No Docs

### ISSUE THREAD

**Issue by br-designer** [ethercreative/simplemap#385]
@Tam Doc's like doesn't work: https://docs.ethercreative.co.uk/maps

**Comment by knufri** [comment]
Hello @br-designer I stumbled over the same "problem" but you find the docs in the repo iteself: https://github.com/ethercreative/simplemap/tree/v4/docs

Greetings Jan

**Comment by alexjcollins** [comment]
Thanks for flagging. Should be good, now.
