### ISSUE TITLE
polyfill.io is not safe

### ISSUE THREAD

**Issue by JPC-ECEDI** [ethercreative/simplemap#395]
The polyfill.io library has been sold to a chinese company named Funnull that is not considered trustworthy. We believe this poses a grave security threat and the library is now considered unsafe.

https://github.com/ethercreative/simplemap/blob/c51add1b905427111680a7066bf68a37d1233e47/src/fields/MapField.php#L477

Proposed resolution

The library could be replaced with fastly.

`$view->registerJsFile('ttps://polyfill-fastly.io/v3/polyfill.js?flags=gated&features=default%2CIntersectionObserver%2CIntersectionObserverEntry'); 
`

**Comment by joelstrom** [comment]
+1 to this issue, we are using this addon on multiple Craft 3 & 4 sites and they are all affected.

**Comment by Tam** [comment]
Thanks for alerting us, I've updated the plugin for Craft 3, 4, & 5.

**Comment by MattWilcox** [comment]
Might be wise to mark those as Critical updates. 
PS: Thanks for the quick update!

(mad morning of checking client sites for patches... can you tell?)

**Comment by jamie-s-white** [comment]
@Tam the Craft 3 version of this update needs another tweak:

https://github.com/ethercreative/simplemap/blob/v3/composer.json

composer.json still lists version 3.9.4 of the plugin, so when we do composer update, we are not getting the updates.

Also, the tag is v3.9.4, not 3.9.4 (but I don't think this makes a difference).

**Comment by Ticolyle** [comment]
> @Tam the Craft 3 version of this update needs another tweak:
> 
> https://github.com/ethercreative/simplemap/blob/v3/composer.json
> 
> composer.json still lists version 3.9.4 of the plugin, so when we do composer update, we are not getting the updates.
> 
> Also, the tag is v3.9.4, not 3.9.4 (but I don't think this makes a difference).

Looks like there is a PR for this fix ready to go as well: https://github.com/ethercreative/simplemap/pull/400

**Comment by bartdigitalpulse** [comment]
This marked as critical for version 3.9.5 but not for version 4.0.8 @Tam
