### ISSUE TITLE
Can the address be exported in components?

### ISSUE THREAD

**Issue by idahotallpaul** [ethercreative/simplemap#4]
Looks like right now the plugin exports lat, lng, zoom and address, but address is a string. Is there a way to grab address, city, state & zip individually? If the address was broken into its component parts the plugin would be perfect for what I need.

Thanks.

**Comment by shornuk** [comment]
Agree. Would be a nice feature! +1 from me!

**Comment by Tam** [comment]
Added in 56c07d8 (v1.1.1)
