### ISSUE TITLE
Not working in IE11 (probably dispatchEvent)

### ISSUE THREAD

**Issue by ElephantTrail** [ethercreative/simplemap#40]
Hi,

In IE11 the plugin is not loading in Craft CMS. We did some researching and think it is because of the dispatchEvent in:

`
SimpleMap.LoadGoogleAPI.LoadMapsApi = function (key, locale) {
		google.load('maps', '3', {
			other_params: 'libraries=places&key=' + key +
			'&language=' + locale.replace('_', '-') +
			'&region=' + locale,
			callback: function () {
				document.dispatchEvent(new Event('SimpleMapsGAPILoaded'));
			}
		});
	};
`

The error message is: "Object doesn't support this action"
Could you fix this?

**Comment by Tam** [comment]
We don't support IE, sorry.
