### ISSUE TITLE
Cannot find 3.9.5 release

### ISSUE THREAD

**Issue by vandres** [ethercreative/simplemap#401]
![grafik](https://github.com/ethercreative/simplemap/assets/1436383/5ae14417-12c3-4dd7-9d07-33792bc1c028)

Am I doing something wrong?

**Comment by joelstrom** [comment]
Any update on this one? Facing the same issue and thinking if we should patch it ourselves or wait for an official version

**Comment by alexjcollins** [comment]
We'll be releasing an update on Monday

**Comment by AFancyUsername** [comment]
Any update on this?

**Comment by Tam** [comment]
Fixed
