### ISSUE TITLE
Can a I pull business name in parts?

### ISSUE THREAD

**Issue by brandondeweese** [ethercreative/simplemap#42]
Hi, I can get everything I need from "parts" except for the business name. Is there an easy way to achieve this or no?

Thanks.

**Comment by Tam** [comment]
Unfortunately there is no way to get the business name from the data that SimpleMap stores, but it is certainly something we will be able to add in the future. In the meantime, it may be possible for you to get the business name using Google's [Places API](https://developers.google.com/maps/documentation/javascript/places).

**Comment by bphippen** [comment]
I also would love to see something like this. Maybe add the place_id to the parts if one exists?

**Comment by Tam** [comment]
We've updated the plugin to work with various other mapping services, and since this is very specific to a single service we won't be adding support for it.
