### ISSUE TITLE
Multilanguage - "not translatable"-checkbox ignored

### ISSUE THREAD

**Issue by akuales** [ethercreative/simplemap#43]
I use this magnificent plugin in a multi-language environment.
When creating a simplemap-field I checked the "not translatable" box, because I need the plugin only to display a marker in the frontend - which is the same in every language.

When I set the marker-position in one language, it gets saved correctly, but in all other languages the marker has still the default lng/lat-values.

I'm using the latest release (1.5.1).
Reading through the issue-section it seems that this is a bug, that was already fixed?

**Comment by Tam** [comment]
Fixed in [v1.6.0](https://github.com/ethercreative/simplemap/releases/tag/v1.6.0)
