### ISSUE TITLE
Upgrade to 1.6 doesn't update non-translatability for existing location field values.

### ISSUE THREAD

**Issue by monachilada** [ethercreative/simplemap#44]
I just upgraded from 1.5.1, went into some of my entries where location fields (set as non-translatable) were previously saved, and the locations didn't appear. Going into the database and manually changing the ownerLocale to NULL made the field values show up again when editing the entries. this seems like a pretty big deal, as the casual observer will see a bunch of fields that are suddenly empty after the upgrade. Fortunately I didn't have too many and had the wherewithal to check the DB and figure out what was going on. Let me know if you need more info.

**Comment by Tam** [comment]
Fixed in [v1.6.1](https://github.com/ethercreative/simplemap/releases/tag/v1.6.1). It's like nothing ever happened.
