### ISSUE TITLE
Lat/Lng validation issues on manual marker position.

### ISSUE THREAD

**Issue by bradarnett** [ethercreative/simplemap#46]
When I try to save after clicking on the map to select a marker position I'm getting the following error, is it possible to disable this validation or auto-round up to the nearest valid value?

![map issue](https://user-images.githubusercontent.com/17981427/27388478-854e69c2-5693-11e7-8117-845cbcb5e568.png)

**Comment by Tam** [comment]
Fixed in v1.6.2!

**Comment by bradarnett** [comment]
Ah brilliant. Thanks!
