### ISSUE TITLE
location param only works with lat/lng values

### ISSUE THREAD

**Issue by designkarma** [ethercreative/simplemap#50]
Hi guys. This plugin is going to really useful on a site I'm building but I can't get it working right. For some reason searching/sorting only works when I pass in lat/lng values, but not when I pass in a string like 'Manchester, UK'. In the latter case I don't get an error, I just get a list of all entries, when it should only return about 5.

So this works:

`{% set entries = craft.entries.serviceCentreMap({
	location: ({'lat': 53.480759, 'lng': -2.242631}),
	radius: 10,
	unit: 'mi'
}).order('distance') %}`

But this doesn't:

`{% set entries = craft.entries.serviceCentreMap({
	location: 'Manchester, UK',
	radius: 10,
	unit: 'mi'
}).order('distance') %}`

Any ideas?

**Comment by Tam** [comment]
Are you getting any errors in either `Craft.log` or `SimpleMap.log`?

**Comment by Tam** [comment]
It's also possible that your Google Maps API key doesn't have the Geocoding API enabled, which would mean searching by address would fail.

**Comment by designkarma** [comment]
Hi Tam thanks for getting back to me. This particular issue was a little while ago and I'm all sorted now. Not sure what the issue was but you're probably right about the Geocoding. Thanks.
