### ISSUE TITLE
Is it possible to query locations based on information from a part of the address?

### ISSUE THREAD

**Issue by timknight** [ethercreative/simplemap#52]
This might be my neophyte showing with Craft ElementCriteriaModel but I figured maybe this would be simplemap specific. Is it possible to do a query of all items within a section based on a value within `[field].parts`? Something like:

```twig
{% set members = craft.entries.section('members').addressField({
  country: "United States"
})
```

**Comment by Tam** [comment]
You can't at the moment. In this case you'd want to use `location: "United States", radius: 2745` but this has the down side of searching every location in a 2745km radius around what Google considers to be the centre of the US (which is *State Beach, Independence, Kansas* apparently). This means you'd also be searching all of Mexico, Guatemala, and Honduras, nearly all of Cuba, and a large chunk of Canada. And this is only if we pretend Alaska doesn't exist, and we forget about Guam, Puerto Rico, and all the other US overseas territories (I'm sure they're used to it).

I can definitely see being able to restrict your search by geographic region being useful. I'll add it to the list!

**Comment by timknight** [comment]
Awesome Tam, thanks for adding it to the list. In terms of search, I just think it would be great if you're able to query and search any portion of the address you have stored in the database for addresses you've added using Simple Map on the CP site regardless of it's relationship in distance. Keep up the great work with Simple Map, it's been awesome to have it in the Craft community!

**Comment by Tam** [comment]
[Added in v3.1.0](https://github.com/ethercreative/simplemap/releases/tag/v3.1.0)!

**Comment by Tam** [comment]
I mean v3.0.4. They both have 3s, it's fine.
