### ISSUE TITLE
Search results different on local env to live env

### ISSUE THREAD

**Issue by shornuk** [ethercreative/simplemap#54]
Hi, 

Not sure if this is a Simplemap issue, but we're having some strange behaviour. Working on a site locally, I've a search form that searches entries based solely on the location field. All works fine. For example, a typical search with a radius gives 20-30 results. 
We then pushed this to staging server and the search now returns zero or 1 to 2 results. Exact same database copied down from the live/staging server to local. Always works on local. I'm at a loss on what to check?

**Comment by Tam** [comment]
Can you let me know what versions of PHP, MySQL, & Craft you're using?

**Comment by shornuk** [comment]
Sure, 
Local:
Craft 2.6.2991, PHP 7.1 and MariaDB 10.2.9
Live
Craft 2.6.2991, PHP 7.1 and MariaDB 10.2.8

**Comment by Tam** [comment]
Are you getting any errors in either `craft.log` or `simplemap.log`? Also, can you compare the contents of your `craft_simplemap_maps` tables on your local & live envs to make sure they're the same?

**Comment by shornuk** [comment]
Hi, nothing in the logs, no `simplemap.log` being created. Comparing the `craft_simplemap_maps` tables, they are exactly the same.

**Comment by Tam** [comment]
If you refresh the page that's running the location search query, then immediately check your `craft.log` you should be able to find something like this:

```
(6371 * acos(cos(radians(51.270363)) * cos(radians(craft_simplemap_maps.lat)) * cos(radians(craft_simplemap_maps.lng) - radians(0.522699)) + sin(radians(51.270363)) * sin(radians(craft_simplemap_maps.lat)))) AS distance
```

Could you send me the above for both dev & live?

**Comment by shornuk** [comment]
Hi, have just done this, but not getting anything in the logs that looks like the above.

**Comment by shornuk** [comment]
Hi, 
Just to add a little further info. The site is hosted on a Forge/Linode set up. We cloned it across to a Cloudways server to test and it works there, so looks like it's something to do with the server setup/config. Any ideas on what might affect it? Only thing I can see different from a quick look through the server info in the CP is `cgi.fix_pathinfo` is set to 1 locally, and on the server that works, but 0 on the one that doesn't.

**Comment by Tam** [comment]
@shornuk That's a bit beyond me I'm afraid! I've never used Forge or Cloudways, so I can't really help. If the `cgi.fix_pathinfo` is the only difference, the only thing I can think of doing is setting that to the same as the working servers to see if it helps.
