### ISSUE TITLE
Error at save new user

### ISSUE THREAD

**Issue by pixeldeluxe** [ethercreative/simplemap#56]
Very nice plugin! Keep up the good work!
When I use the field in a User profile it won't save:
in_array() expects parameter 2 to be array, null given

**Comment by Tam** [comment]
What version of Craft & the plugin are you using, and can you paste the full stack trace?

**Comment by pixeldeluxe** [comment]
Oops, I'm sorry for the fuzz! I guess another plugin was the trouble maker.
