### ISSUE TITLE
Is it possible to access an addition to a streetnumber is a seperate attribute

### ISSUE THREAD

**Issue by manomoul** [ethercreative/simplemap#57]
Oud address number is made of 2 parts ,
{streetname} 4E 205
I am able to access {{contact.address.parts.street_number}} as a seperate attribute, but I cannot separately output  205. 
{{contact.address.parts.street_number}} outputs only 4E, which makes it difficult to format the address in the templates.

**Comment by Tam** [comment]
I'm not sure exactly what you're after, but is sounds like you're not getting the entire address you need. You can find a list of all the available address parts [here](https://developers.google.com/maps/documentation/geocoding/intro#Types), hopefully one of these will return the data you need.

It might help if you dump out the data you're receiving to see if what you're after is available. You can do this (when in [`devMode`](https://craftcms.com/docs/config-settings#devMode)) by writing `{{ dump(contact.address.parts) }}` in your template

**Comment by manomoul** [comment]
I did these things before submitting this issue. What I mean , now with a concrete example:
- I put this address in simplemap: Dok-Noord 4E 205 
now I want this result in html:
`<div class="address-block">
Dok-Noord 4E 205<br>
9000 Gent<br>
</div>`

This is atm not possible with the simplemap plugin as I see it. 
{{contact.address.parts.route}} {{contact.address.parts.street_number}} outputs Dok-Noord 4E without the "255".

**Comment by Tam** [comment]
It's strange that Google isn't returning that part of the address. It looks like your best bet is trying one of the following:

If you want to get the first line of the address, you can do this:

```twig
{{ contact.address.address|split(',')[0] }}
```

If you want to output the address on multiple lines, you can try this:

```twig
{{ contact.address.address|replace(',', '<br>')|raw }}
```

**Comment by manomoul** [comment]
Ok, thank you for clarifying. I didn't know whether it was the plugin or Google.
