### ISSUE TITLE
Feature request: GraphQL support

### ISSUE THREAD

**Issue by markhuot** [ethercreative/simplemap#60]
I’m working on a plug-in that exposes Craft fields over a GraphQL endpoint. To do this the field needs to have two additional methods to expose the field schema to GraphQL.

There’s a request for this over on the CraftQL repo:

https://github.com/markhuot/craftql/issues/30#issuecomment-348067568

Not sure if this is something you want to support. If so, yay! If not, no worries, I can support it unofficially through some Yii Behavior monkey patching.

**Comment by Tam** [comment]
[Added in v3.1.0](https://github.com/ethercreative/simplemap/releases/tag/v3.1.0)
