### ISSUE TITLE
Boundary restriction fields need decimals

### ISSUE THREAD

**Issue by juresrpcic** [ethercreative/simplemap#64]
Currently the boundary restriction fields are limited to integers - Google supports floating point numbers here and they are often required (whole lat/long numbers aren't very precise).

Example of Google-friendly JSON for boundaries that works with decimals:
```js
"types": ["establishment"],
"bounds": {
"north": 51.510096,
"east": -0.127851,
"south": 51.502721,
"west": -0.142560
}
```

Thanks.

**Comment by Tam** [comment]
Fixed in v3.1.2
