### ISSUE TITLE
Error when adding a map to a global set

### ISSUE THREAD

**Issue by Radiergummi** [ethercreative/simplemap#65]
### Description
When you add a map field to a global set section, the `could not save global set.` message appears. Logs in debug bar show no further errors though.  
Once I add the same field to the users layout, it works fine.

### Steps to reproduce
1. Install simplemap in Craft 3 from plugin store
2. Add a valid API key
3. Create a new map field with defaults
4. Add the field to an existing global set section

### Additional info
Craft version: 3.0.0-RC1

**Comment by Tam** [comment]
This looks like an issue with the way Craft saves global sets. I've submitted an issue, so we'll have to wait and see!

**Comment by Tam** [comment]
Fixed in v3.1.3

**Comment by Radiergummi** [comment]
Weeeee, thanks! 👌

Tam <notifications@github.com> schrieb am Mo., 18. Dez. 2017, 16:47:
