### ISSUE TITLE
Settings page translations broken

### ISSUE THREAD

**Issue by Radiergummi** [ethercreative/simplemap#66]
The settings labels are not being replaced currently:

<img width="284" alt="bildschirmfoto 2017-12-08 um 12 12 31" src="https://user-images.githubusercontent.com/6115429/33763522-1cdcac88-dc11-11e7-9074-8e19991df1eb.png">

**Comment by Tam** [comment]
What language is your CP in?

**Comment by Tam** [comment]
Fixed in v3.1.2

**Comment by Radiergummi** [comment]
Hey @Tam, sorry, was out of the office the last week. It's in german, but I see you fixed that already, so thank you ✌️
