### ISSUE TITLE
When adding extra locale, (some) entries lose the map coordinates

### ISSUE THREAD

**Issue by boldenamsterdam** [ethercreative/simplemap#67]
Hello,

I have the following issue in my project. I have a project with a single locale and I want to add a second locale. After successfully adding the 2nd locale some of the entries (not all of them) lose the map coordinations. In the database the "simplemap_maps" table remains the same. All the other field work fine with the extra locale and they can even be translatable without any issue. It is only that some entries lose the information of the map coordinates/address.

The entry that uses the map plugin has the following properties:
![screen shot 2017-12-08 at 15 33 30](https://user-images.githubusercontent.com/7466604/33770286-50bfc226-dc2d-11e7-8481-4462c7cf3e53.png)

I use the latest version of Craft CMS (2.6.3000) and the latest version of simple map plugin (1.8.1). 

Did anyone experience something similar?

**UPDATE**
Table "simplemap_maps" get the following:
![screen shot 2017-12-08 at 15 51 52](https://user-images.githubusercontent.com/7466604/33771030-dd9764b8-dc2f-11e7-9128-e5985e68f56b.png)
The 1st entry is with "nl_nl" locale is the original and is correct. The 2nd entry with "null" locale should actually be "en". And the rest of information is not filled in. So I think there it goes wrong..

**Comment by Tam** [comment]
Do you have a backup of the database before you added the extra locale? Also, were there any similarities between the entries that lost their data?

**Comment by Tam** [comment]
Closing this due to lack of feedback.
