### ISSUE TITLE
Minor URL update required

### ISSUE THREAD

**Issue by peteralewis** [ethercreative/simplemap#68]
In the file /simplemap/SimpleMapPlugin.php (v2 Branch):
```
public function getReleaseFeedUrl()
{
	return 'https://raw.githubusercontent.com/ethercreative/SimpleMap/master/releases.json';
}
```
Needs to be updated to:
`https://raw.githubusercontent.com/ethercreative/SimpleMap/v2/releases.json`

Noticed that v3 branch doesn't have a releases file - I assume that's by design.

**Comment by Tam** [comment]
That's fixed, thanks for letting me know!
