### ISSUE TITLE
Distance is Not Working

### ISSUE THREAD

**Issue by bfopma** [ethercreative/simplemap#69]
This looks like it may not have been working for a while but I noticed that the map distance (distance between two lat/lng) was always returning 'null'. This issue looks like it is on line 406 of services/SimpleMapService.php of the v2 branch:

`if (!$this->searchLatLng || !$this->searchEarthRad) return null;`

This will always return null since as far as I can tell $this->searchEarthRad no longer exists. It may need to be changed to:

`if (!$this->searchLatLng || !$this->searchDistanceUnit) return null;`

Please update if possible!

Thanks,
Brady

**Comment by Tam** [comment]
Fixed in v1.8.2
