### ISSUE TITLE
Save subpremise to db

### ISSUE THREAD

**Issue by timkelty** [ethercreative/simplemap#72]
I'm seeing `subpremise` (in this case, the room/suite $) in the returned api from google, but it isn't getting written to the db.

**Comment by Tam** [comment]
Could you give me an example address to test agains?

**Comment by timkelty** [comment]
I first tried the address with the subpremise (Suite #) in the address. Unfortunately that kills the autocomplete.

Then I tried searching for the org name. Autocomplete works there and the API google places response api response has `{long_name: "#101", short_name: "#101", types: ["subpremise"]}` in the `result.address_components` array (but doesn't end up in the DB.

**Address**
2944 Fuller Avenue Northeast #101, Grand Rapids, MI, United States

`simplemaps.parts`
```json
{"street_number":"2944","street_number_short":"2944","route":"Fuller Avenue Northeast","route_short":"Fuller Ave NE","neighborhood":"Creston","neighborhood_short":"Creston","locality":"Grand Rapids","locality_short":"Grand Rapids","administrative_area_level_2":"Kent County","administrative_area_level_2_short":"Kent County","administrative_area_level_1":"Michigan","administrative_area_level_1_short":"MI","country":"United States","country_short":"US","postal_code":"49505","postal_code_short":"49505","postal_code_suffix":"3784","postal_code_suffix_short":"3784"}
```

**Address**
Alzheimer's Association – Greater Michigan Chapter, West Michigan Office

`simplemaps.parts`
```json
{"street_number":"2944","street_number_short":"2944","route":"Fuller Avenue Northeast","route_short":"Fuller Ave NE","neighborhood":"Creston","neighborhood_short":"Creston","locality":"Grand Rapids","locality_short":"Grand Rapids","administrative_area_level_2":"Kent County","administrative_area_level_2_short":"Kent County","administrative_area_level_1":"Michigan","administrative_area_level_1_short":"MI","country":"United States","country_short":"US","postal_code":"49505","postal_code_short":"49505","postal_code_suffix":"3784","postal_code_suffix_short":"3784"}
```

**Comment by Tam** [comment]
SimpleMap doesn't use the Places API (yet, #42). We use the Geocoding API to get details about the given location, which doesn't seem to include `subpremise` for some reason. This is something we're looking to add in the future.

**Comment by timkelty** [comment]
> SimpleMap doesn't use the Places API

Ah ok. Well…except that I am seeing `subpremise` returned from the google response (when I use the org name).
