### ISSUE TITLE
Import via Feed Me

### ISSUE THREAD

**Issue by bymayo** [ethercreative/simplemap#77]
It would be good if we could import map content via Feed Me plugin:

https://verbb.io/craft-plugins/feed-me/docs/developers/field-types

**Comment by Tam** [comment]
SimpleMap already supports Feed Me for Craft 2. We'll add support for the Craft 3 version once it's released!

**Comment by bymayo** [comment]
Sorry, this is my bad. I didn't realise until I just read your changelog! Whoops.
