### ISSUE TITLE
FR: Options to store/override address components

### ISSUE THREAD

**Issue by timkelty** [ethercreative/simplemap#78]
In the field options, I could specific additional address components to display (street address, organization name, room number, line 2, etc).

Those fields would then show with the map and populate on a location selection (as lat/lng do now).

The reason for this is ensure an accurate address and the ability to provide an override to formatting. Currently I've had to add an "Additional address info" field for things like room/bldg number, as they are not saved with the autocomplete selection. I've also had clients want their address formatted differently than what the google results return.

**Comment by JimboM4CK** [comment]
2nd this, it seems to be stripping subpremise, so I can't select the unit or room number.

**Comment by Tam** [comment]
You can now manage the address parts in the latest release ([3.4.0](https://github.com/ethercreative/simplemap/releases/tag/3.4.0)).
