### ISSUE TITLE
Invisible map when in a secondary tab

### ISSUE THREAD

**Issue by paul-frost** [ethercreative/simplemap#8]
When I include the simplemap field type in a secondary tab in the field layout for the section the map is invisible (just grey box). The location bar updates if I drag the pin around, just no map tiles visible.
If I put the field on the primary tab it works fine.

I've had similar problems before with Google maps in ExpressionEngine where it didn't work in hidden tabs. The solution was that the map needed to be redrawn and needs some js to do it.

**Comment by bomanden** [comment]
Have the same issue on craft 2.6.2xxx. I'll check back to see if this issue is fixed. 
Would be nice to move it to another tab as it takes up space in the layout.

**Comment by Tam** [comment]
Fixed in [v1.2.1](https://github.com/ethercreative/simplemap/releases/tag/v1.2.1)
