### ISSUE TITLE
No longer in plugin store?

### ISSUE THREAD

**Issue by lukeyouell** [ethercreative/simplemap#83]
### Description

Looks like the plugin is no longer listed in the plugin store. Any ideas?

### Additional info

- Craft version: 3.0.0-RC7.1

**Comment by Tam** [comment]
So it's NOT just me! I shall poke P&T.

**Comment by lukeyouell** [comment]
@Tam I installed via composer, but every time I tried to save a new map field it bricked the CP?

**Comment by Tam** [comment]
Weird. I just span up a fresh craft install, added SimpleMap via composer and everything worked fine. Are you getting any errors?

**Comment by lukeyouell** [comment]
Weird, it works now!

I was getting something along the lines of `Unable to getMap() with a null value` when trying to view any page in the CMS after saving a map field. I had to delete the field from the db.
