### ISSUE TITLE
Saving always fails when SimpleMap field is set required

### ISSUE THREAD

**Issue by Stalinko** [ethercreative/simplemap#87]
I have an entry with a field "Location" type SimpleMap.
This field is set "required" in the entry field layout.
This field has a value, it's not empty.

But when I simply fetch a model from DB, change any other simple field and try to save it it always fails with "Location cannot be empty." error.

See this code:

```    $criteria = craft()->elements->getCriteria(ElementType::Entry);
    $criteria->id = $some_id;
    $assessment = $criteria->first();

    $assessment->getContent()->someField = $someValue;
    $success = craft()->entries->saveEntry( $assessment );
    print_r($assessment->getAllErrors()); //says "Location cannot be empty."
    var_dump($assessment->getContent()->location); //null
    var_dump($assessment->location->address); //my address value, a non-empty string
```

I tried to dig into craft/yii code. It uses "getContent()->$field" value for validation which is null in this case. So I have to make this field non-required for the moment, to be able to use and save it.

What do I do wrong? Or it was designed so that this field can not be required?

Craft Version: 2.6
Simple Map Version: 1.8.2

**Comment by Tam** [comment]
SimpleMap stores its data relationally, meaning it's not stored in the main content table (similar to how matrix stores its data). Craft 2 has an issue where it doesn't re-save relational data when saving programatically. You'll have to manually handle re-setting these fields when saving.

Something like
```php
// [...]

$assessment = $criteria->first();

// Get all the fields for this element
$fields = $assessment->getFieldLayout()->getFields();
$referentialFields = array();

// Loop over each field
foreach ($fields as $layoutField)
{
	$field = $layoutField->getField();

	// If the field is relational, re-set the field
	if ($field->getFieldType() instanceof BaseElementFieldType)
	{
		$referentialFields[$field->handle] = 
			$assessment->{$field->handle}->ids();
	}
}

// Add the referential fields back to the element
$assessment->setContentFromPost($referentialFields);

$assessment->getContent()->someField = $someValue;

// [...]
```
*might* work. If not you'll have to manually re-pass the value to the map field.
