### ISSUE TITLE
Output Google Maps API key on front-end

### ISSUE THREAD

**Issue by codebybrassneck** [ethercreative/simplemap#9]
I just wondered if it was possible to get the API Key used by the settings out on the front-end in your twig templates? It'd be really useful, rather than having to store it in a separate field for use in your templates.

All the best,
Steve

**Comment by Tam** [comment]
Added in v1.2.3

**Comment by bymayo** [comment]
@Tam Would be good if this was added to the docs (Or at least I can't find it?!). 

Ended up wondering if it was possible, and searching Issues
