### ISSUE TITLE
FR: Add an option to 'clear' the field after it has been populated

### ISSUE THREAD

**Issue by petehjfd** [ethercreative/simplemap#93]
### Description
I'm outputting entries as map markers on the front-end. I only want to show a map marker if the map field has been completed.

However, once a location has been selected, it doesn't seem to be possible to clear the field. There's no way to return that field to being empty. So once an entry has been assigned to a location, it can never not be assigned to a location.

Unless I'm missing something?

Maybe there could be a 'clear' button?

### Steps to reproduce

1. Add an entry and select a location on the map
2. Decide that you no longer want the map field to be populated
3. Be sad that you can't clear the field :(

### Additional info

- Craft version: 3.0.0-RC10.1
- SimpleMap version: 3.3.1
- PHP version: 7.1.1
- Database driver & version: MySQL 5.6.35

**Comment by Tam** [comment]
Added in 3.4.6
