### ISSUE TITLE
Upgrading Craft 2 -> 3 whilst keeping map data

### ISSUE THREAD

**Issue by iparr** [ethercreative/simplemap#95]
### Description

We have been happily using the Craft 2.x version of this plugin. I am in the process of upgrading the website to Craft 3. This has gone well so far, and all content has been ported over apart from that which is facilitated using this plugin (although in all fairness, I don't utilise any plugins that are responsible for fields).

I'm after for a way to migrate this map content from v2 to v3.

Regardless, thank you for your work on this plugin.

### Steps to reproduce

1. Perform Craft 2 -> 3 upgrade successfully.
2. Edit page with 'Map' field - see `Unable to find component class 'SimpleMap_Map'.` message.
3. Install plugin from Plugin store.
4. Edit fields. The field type “SimpleMap_Map” could not be found.`. Choose 'Map' as field type. Warning that this will destroy the content, but not sure of any alternative!
5. When editing entry, all maps fields are now reset.

There is, however, a bunch of familiar content in the `craft_simplemap_maps` table in the database. I'm just unsure of how to glue the bits together!

### Additional info

- Craft version: 3 RC11.
- SimpleMap version: 3.3.2 (from 1.7.0)
- PHP version: 7.1.14
- Database driver & version: MySQL 5.7.21
- Other Plugins: Redactor, Element API.

**Comment by Pautomagi** [comment]
Ive been having the same issue.

My workaround for now was to export all the rows in `craft_simplemap_maps` into a text editor.

Wrap every line in `( ),` so it looks something like this :

```
('1', '567', '23', '1', '59.21134570', '10.99575750', '15', 'here is the address', 'Here is the json object', '2017-07-10 07:54:25', '2018-06-01 11:16:38', '2eac9606-8709-4fd6-a022-613c8c2b74b7'),
```

Then what you do is you remove the first column on each line, which corresponds to the ID in the old table.
( I used a regex like this `^([^,]+), ` and replace with `(`

Next up you want to do a find replace on `'no', ` and remove that as well.

ps: If you are running a multisite (having multiple locales i.e) you need to run this twice replacing the `1` in the third column with whatever siteId the other one carries.

Next up is to build the query

```
insert into craft_simplemaps(ownerId, fieldId, ownerSiteId, lat, lng, zoom, address, parts, dateCreated, dateUpdated, uid) VALUES (
*** THIS IS WHERE YOU PASTE THE LINES ***
)
```

Its a poor mans guide but at least I didnt have to manually enter a thousand addresses.
I do not take any responsibility for anything that might break here, so keep a backup before you go down this road.


ping @iparr if you want to give this a go.

**Comment by outline4** [comment]
any news on this?

**Comment by jonXmack** [comment]
After messing around with @Pautomagi's suggestion and getting nowhere I went a different route and just copied it all over, table to table...

```
INSERT INTO craft_simplemaps (ownerId, ownerSiteId, fieldId, lat, lng, zoom, address, parts, dateCreated, dateUpdated, uid)
SELECT ownerId, ownerLocale__siteId, fieldId, lat, lng, zoom, address, parts, dateCreated, dateUpdated, uid
FROM craft_simplemap_maps
```

cc @outline4 if you're still having a hard time

**Comment by Tam** [comment]
We've added an actual migration path from Craft 2 to 3 in the latest release ([3.4.0](https://github.com/ethercreative/simplemap/releases/tag/3.4.0)).
