### ISSUE TITLE
Simplemap breaks ResaveElements job

### ISSUE THREAD

**Issue by ostark** [ethercreative/simplemap#96]
### Description

When Craft's ResaveElements job is handled by console queue `craft queue/run` or [my little plugin](https://github.com/ostark/craft-async-queue/) which does basically the same, and a simplemap field involved, it failes to execute that job as `Request::getIsPost()` does not exist on the console.

### Steps to reproduce & Additional info

https://github.com/ostark/craft-async-queue/issues/5

**Comment by Tam** [comment]
Fixed!

**Comment by ostark** [comment]
Thanks @Tam!

**Comment by nfourtythree** [comment]
Hey @Tam thanks for fixing this, it popped up on a project I am currently working on.

Is it possible to push a release for this so I can `composer update` it?

Thanks!

**Comment by Tam** [comment]
Ha, whoops! I've pushed a new release

**Comment by nfourtythree** [comment]
Thanks!
