### ISSUE TITLE
Sample code for rendering multiple maps on the same page

### ISSUE THREAD

**Issue by skramstad** [ethercreative/simplemap#98]
### Description

Is there a sample code I can use to render multiple maps on the same page?

### Additional info

- Craft version: Craft 3.0.2
- SimpleMap version: 3.3.3

**Comment by Tam** [comment]
Maps _currently_ doesn't handle rendering maps on the front-end. There are some examples of how to output maps in the readme (https://github.com/ethercreative/simplemap#displaying-a-map) but how you output the map really depends on the service you want to use. I recommend checking the docs of your choosen service or searching on StackOverflow for examples.
